%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%          Generated by MATLAB 25.1 and Fixed-Point Designer 25.1          %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%#codegen
function [Rtri, valid] = covariance_core_fixpt(samp_re, samp_im, samp_valid, frame_start)
%PL block v4: streaming covariance - SCALAR-ACCESS accumulation.
% v3 used R(:) = R + (buf*buf'): a whole-matrix read-modify-write. HDL
% conformance warned "'R': RAM mapping failed ... non-scalar sub-matrix
% access" / "unable to apply vector streaming". Under StreamLoops that
% matrix RMW is scheduled across sub-rate phases and the R read races
% its own writeback: generated RTL retains ~1 snapshot of 256 (verified:
% MathWorks' own generated TB fails identically in Vivado AND Verilator
% while the sequential fixed-point MATLAB sim passes). v4 does what the
% warning asks: explicit scalar element updates only.
    fm = get_fimath();

    persistent Rr Ri buf_r buf_i pos scount;
    if isempty(Rr)
        Rr = fi(zeros(4,4), 1, 16, 6, fm); Ri = fi(zeros(4,4), 1, 16, 6, fm);
        buf_r = fi(zeros(4,1), 1, 16, 13, fm); buf_i = fi(zeros(4,1), 1, 16, 13, fm);
        pos = fi(int32(0), 0, 2, 0, fm); scount = fi(int32(0), 0, 9, 0, fm);
    end
    if frame_start
        for i=1:4
            for j=1:4
                Rr(i,j) = 0; Ri(i,j) = 0;      % scalar resets
            end
        end
        pos(:) = int32(0); scount(:) = int32(0);
    end
    valid = false;
    Rtri = fi(complex(zeros(10,1)), 1, 16, 14, fm);
    if samp_valid
        buf_r(pos+fi(1, 0, 1, 0, fm)) = samp_re; buf_i(pos+fi(1, 0, 1, 0, fm)) = samp_im;
        if pos == fi(3, 0, 2, 0, fm)
            for i = 1:4                          % scalar-only outer product:
                for j = 1:4                      % R(i,j) += x_i * conj(x_j)
                    Rr(i,j) = Rr(i,j) + (buf_r(i)*buf_r(j) + buf_i(i)*buf_i(j));
                    Ri(i,j) = Ri(i,j) + (fi_signed(buf_i(i)*buf_r(j)) - buf_r(i)*buf_i(j));
                end
            end
            scount(:) = scount + fi(1, 0, 1, 0, fm);
            pos(:) = int32(0);
            if scount == fi(256, 0, 9, 0, fm)
                idx = fi(1, 0, 4, 0, fm);
                for i=1:4
                    for j=i:4
                        Rtri(idx) = complexx(Rr(i,j)*(fi(2^-8, 0, 16, 23, fm)), Ri(i,j)*(fi(2^-8, 0, 16, 23, fm)));
                        idx(:) = idx + fi(1, 0, 1, 0, fm);           % *(2^-8) = /256, shift
                    end
                end
                valid(:) = true;
                scount(:) = int32(0);
            end
        else
            pos(:) = pos + fi(1, 0, 1, 0, fm);
        end
    end
end



function c = complexx(varargin)
    coder.inline( 'always' );
    if nargin==2
        re = varargin{ 1 };
        im = varargin{ 2 };
        if isfi( re ) && isfi( im )
            % Choose wider type
            NT = fixed.aggregateType( re, im );
            c = complex( fi( re, NT ), fi( im, NT ) );
        else
            c = complex( re, im );
        end
    elseif nargin==1
        c = complex( varargin{ 1 } );
    end
end


function y = fi_signed(a)
    coder.inline( 'always' );
    if isfi( a ) && ~(issigned( a ))
        nt = numerictype( a );
        new_nt = numerictype( 1, nt.WordLength + 1, nt.FractionLength );
        y = fi( a, new_nt, fimath( a ) );
    else
        y = a;
    end
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Nearest',...
	     'OverflowAction', 'Saturate', 'ProductMode', 'SpecifyPrecision',...
	     'ProductWordLength', 40,...
	     'ProductFractionLength', 30,...
	     'SumMode', 'SpecifyPrecision',...
	     'SumWordLength', 40,...
	     'SumFractionLength', 30,...
	     'CastBeforeSum', true);
end
