// -------------------------------------------------------------
// 
// File Name: C:\Users\Shashank Madhusudan\OneDrive\Desktop\Radar-Aided-Beam-Tracking\codegen\covariance_core\hdlsrc\covariance_core_fixpt_tb.v
// Created: 2026-07-19 15:08:49
// 
// Generated by MATLAB 25.1, MATLAB Coder 25.1 and HDL Coder 25.1
// 
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Design base rate: 0.0125
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: covariance_core_fixpt_tb
// Source Path: 
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module covariance_core_fixpt_tb;



  reg  clk;
  reg  reset;
  wire enb;
  wire valid_done;  // ufix1
  wire ce_out;
  wire valid_done_enb;  // ufix1
  reg [15:0] Rtri_re_0_addr;  // ufix16
  wire valid_lastAddr;  // ufix1
  wire resetn;
  reg  check2_done;  // ufix1
  wire Rtri_re_0_done;  // ufix1
  wire Rtri_re_0_done_enb;  // ufix1
  wire Rtri_re_0_active;  // ufix1
  reg [15:0] samp_re_addr;  // ufix16
  wire [15:0] frame_start_addr_delay_1;  // ufix16
  wire tb_enb;
  wire phase_1;
  reg signed [31:0] fp_frame_start;  // sfix32
  reg  rawData_frame_start;
  reg signed [31:0] status_frame_start;  // sfix32
  reg  holdData_frame_start;
  reg  frame_start_offset;
  wire frame_start;
  wire [15:0] samp_valid_addr_delay_1;  // ufix16
  reg signed [31:0] fp_samp_valid;  // sfix32
  reg  rawData_samp_valid;
  reg signed [31:0] status_samp_valid;  // sfix32
  reg  holdData_samp_valid;
  reg  samp_valid_offset;
  wire samp_valid;
  wire [15:0] samp_im_addr_delay_1;  // ufix16
  reg signed [31:0] fp_samp_im;  // sfix32
  reg signed [15:0] rawData_samp_im;  // sfix16_En13
  reg signed [31:0] status_samp_im;  // sfix32
  reg signed [15:0] holdData_samp_im;  // sfix16_En13
  reg signed [15:0] samp_im_offset;  // sfix16_En13
  wire signed [15:0] samp_im;  // sfix16_En13
  wire samp_re_active;  // ufix1
  wire samp_re_enb;  // ufix1
  wire [15:0] samp_re_addr_delay_1;  // ufix16
  reg signed [31:0] fp_samp_re;  // sfix32
  reg signed [15:0] rawData_samp_re;  // sfix16_En13
  reg signed [31:0] status_samp_re;  // sfix32
  reg signed [15:0] holdData_samp_re;  // sfix16_En13
  reg signed [15:0] samp_re_offset;  // sfix16_En13
  wire signed [15:0] samp_re_1;  // sfix16_En13
  wire snkDone;
  wire snkDonen;
  wire tb_enb_delay;
  reg [6:0] counter;  // ufix7
  wire phase_1_ctr;
  wire notDone;
  wire signed [15:0] Rtri_re_0;  // sfix16_En14
  wire signed [15:0] Rtri_re_1;  // sfix16_En14
  wire signed [15:0] Rtri_re_2;  // sfix16_En14
  wire signed [15:0] Rtri_re_3;  // sfix16_En14
  wire signed [15:0] Rtri_re_4;  // sfix16_En14
  wire signed [15:0] Rtri_re_5;  // sfix16_En14
  wire signed [15:0] Rtri_re_6;  // sfix16_En14
  wire signed [15:0] Rtri_re_7;  // sfix16_En14
  wire signed [15:0] Rtri_re_8;  // sfix16_En14
  wire signed [15:0] Rtri_re_9;  // sfix16_En14
  wire signed [15:0] Rtri_im_0;  // sfix16_En14
  wire signed [15:0] Rtri_im_1;  // sfix16_En14
  wire signed [15:0] Rtri_im_2;  // sfix16_En14
  wire signed [15:0] Rtri_im_3;  // sfix16_En14
  wire signed [15:0] Rtri_im_4;  // sfix16_En14
  wire signed [15:0] Rtri_im_5;  // sfix16_En14
  wire signed [15:0] Rtri_im_6;  // sfix16_En14
  wire signed [15:0] Rtri_im_7;  // sfix16_En14
  wire signed [15:0] Rtri_im_8;  // sfix16_En14
  wire signed [15:0] Rtri_im_9;  // sfix16_En14
  wire valid;
  wire Rtri_re_0_enb;  // ufix1
  wire Rtri_re_0_lastAddr;  // ufix1
  reg  check1_done;  // ufix1
  reg [1:0] Rtri_re_0_chkcnt;  // ufix2
  wire Rtri_re_0_ignCntDone;  // ufix1
  wire Rtri_re_0_needToCount;  // ufix1
  wire Rtri_re_0_chkenb;  // ufix1
  wire Rtri_re_0_chkdata;  // ufix1
  wire [15:0] Rtri_re_0_addr_delay_1;  // ufix16
  reg signed [31:0] fp_Rtri_re_0_re_0_expected;  // sfix32
  reg signed [15:0] Rtri_re_0_re_0_expected;  // sfix16_En14
  reg signed [31:0] status_Rtri_re_0_re_0_expected;  // sfix32
  reg signed [15:0] Rtri_re_0_ref_hold;  // sfix16_En14
  wire signed [15:0] Rtri_re_0_refTmp;  // sfix16_En14
  wire signed [15:0] Rtri_re_0_ref;  // sfix16_En14
  reg  Rtri_re_0_testFailure;  // ufix1
  reg signed [31:0] fp_Rtri_re_0_re_1_expected;  // sfix32
  reg signed [15:0] Rtri_re_0_re_1_expected;  // sfix16_En14
  reg signed [31:0] status_Rtri_re_0_re_1_expected;  // sfix32
  reg signed [15:0] Rtri_re_1_ref_hold;  // sfix16_En14
  wire signed [15:0] Rtri_re_1_refTmp;  // sfix16_En14
  wire signed [15:0] Rtri_re_1_ref;  // sfix16_En14
  reg  Rtri_re_1_testFailure;  // ufix1
  reg signed [31:0] fp_Rtri_re_0_re_2_expected;  // sfix32
  reg signed [15:0] Rtri_re_0_re_2_expected;  // sfix16_En14
  reg signed [31:0] status_Rtri_re_0_re_2_expected;  // sfix32
  reg signed [15:0] Rtri_re_2_ref_hold;  // sfix16_En14
  wire signed [15:0] Rtri_re_2_refTmp;  // sfix16_En14
  wire signed [15:0] Rtri_re_2_ref;  // sfix16_En14
  reg  Rtri_re_2_testFailure;  // ufix1
  reg signed [31:0] fp_Rtri_re_0_re_3_expected;  // sfix32
  reg signed [15:0] Rtri_re_0_re_3_expected;  // sfix16_En14
  reg signed [31:0] status_Rtri_re_0_re_3_expected;  // sfix32
  reg signed [15:0] Rtri_re_3_ref_hold;  // sfix16_En14
  wire signed [15:0] Rtri_re_3_refTmp;  // sfix16_En14
  wire signed [15:0] Rtri_re_3_ref;  // sfix16_En14
  reg  Rtri_re_3_testFailure;  // ufix1
  reg signed [31:0] fp_Rtri_re_0_re_4_expected;  // sfix32
  reg signed [15:0] Rtri_re_0_re_4_expected;  // sfix16_En14
  reg signed [31:0] status_Rtri_re_0_re_4_expected;  // sfix32
  reg signed [15:0] Rtri_re_4_ref_hold;  // sfix16_En14
  wire signed [15:0] Rtri_re_4_refTmp;  // sfix16_En14
  wire signed [15:0] Rtri_re_4_ref;  // sfix16_En14
  reg  Rtri_re_4_testFailure;  // ufix1
  reg signed [31:0] fp_Rtri_re_0_re_5_expected;  // sfix32
  reg signed [15:0] Rtri_re_0_re_5_expected;  // sfix16_En14
  reg signed [31:0] status_Rtri_re_0_re_5_expected;  // sfix32
  reg signed [15:0] Rtri_re_5_ref_hold;  // sfix16_En14
  wire signed [15:0] Rtri_re_5_refTmp;  // sfix16_En14
  wire signed [15:0] Rtri_re_5_ref;  // sfix16_En14
  reg  Rtri_re_5_testFailure;  // ufix1
  reg signed [31:0] fp_Rtri_re_0_re_6_expected;  // sfix32
  reg signed [15:0] Rtri_re_0_re_6_expected;  // sfix16_En14
  reg signed [31:0] status_Rtri_re_0_re_6_expected;  // sfix32
  reg signed [15:0] Rtri_re_6_ref_hold;  // sfix16_En14
  wire signed [15:0] Rtri_re_6_refTmp;  // sfix16_En14
  wire signed [15:0] Rtri_re_6_ref;  // sfix16_En14
  reg  Rtri_re_6_testFailure;  // ufix1
  reg signed [31:0] fp_Rtri_re_0_re_7_expected;  // sfix32
  reg signed [15:0] Rtri_re_0_re_7_expected;  // sfix16_En14
  reg signed [31:0] status_Rtri_re_0_re_7_expected;  // sfix32
  reg signed [15:0] Rtri_re_7_ref_hold;  // sfix16_En14
  wire signed [15:0] Rtri_re_7_refTmp;  // sfix16_En14
  wire signed [15:0] Rtri_re_7_ref;  // sfix16_En14
  reg  Rtri_re_7_testFailure;  // ufix1
  reg signed [31:0] fp_Rtri_re_0_re_8_expected;  // sfix32
  reg signed [15:0] Rtri_re_0_re_8_expected;  // sfix16_En14
  reg signed [31:0] status_Rtri_re_0_re_8_expected;  // sfix32
  reg signed [15:0] Rtri_re_8_ref_hold;  // sfix16_En14
  wire signed [15:0] Rtri_re_8_refTmp;  // sfix16_En14
  wire signed [15:0] Rtri_re_8_ref;  // sfix16_En14
  reg  Rtri_re_8_testFailure;  // ufix1
  reg signed [31:0] fp_Rtri_re_0_re_9_expected;  // sfix32
  reg signed [15:0] Rtri_re_0_re_9_expected;  // sfix16_En14
  reg signed [31:0] status_Rtri_re_0_re_9_expected;  // sfix32
  reg signed [15:0] Rtri_re_9_ref_hold;  // sfix16_En14
  wire signed [15:0] Rtri_re_9_refTmp;  // sfix16_En14
  wire signed [15:0] Rtri_re_9_ref;  // sfix16_En14
  reg  Rtri_re_9_testFailure;  // ufix1
  wire signed [15:0] Rtri_re_0_im_0_expected_1;  // sfix16_En14
  reg signed [15:0] Rtri_im_0_ref_hold;  // sfix16_En14
  wire signed [15:0] Rtri_im_0_ref;  // sfix16_En14
  reg  Rtri_im_0_testFailure;  // ufix1
  reg signed [31:0] fp_Rtri_re_0_im_1_expected;  // sfix32
  reg signed [15:0] Rtri_re_0_im_1_expected;  // sfix16_En14
  reg signed [31:0] status_Rtri_re_0_im_1_expected;  // sfix32
  reg signed [15:0] Rtri_im_1_ref_hold;  // sfix16_En14
  wire signed [15:0] Rtri_im_1_refTmp;  // sfix16_En14
  wire signed [15:0] Rtri_im_1_ref;  // sfix16_En14
  reg  Rtri_im_1_testFailure;  // ufix1
  reg signed [31:0] fp_Rtri_re_0_im_2_expected;  // sfix32
  reg signed [15:0] Rtri_re_0_im_2_expected;  // sfix16_En14
  reg signed [31:0] status_Rtri_re_0_im_2_expected;  // sfix32
  reg signed [15:0] Rtri_im_2_ref_hold;  // sfix16_En14
  wire signed [15:0] Rtri_im_2_refTmp;  // sfix16_En14
  wire signed [15:0] Rtri_im_2_ref;  // sfix16_En14
  reg  Rtri_im_2_testFailure;  // ufix1
  reg signed [31:0] fp_Rtri_re_0_im_3_expected;  // sfix32
  reg signed [15:0] Rtri_re_0_im_3_expected;  // sfix16_En14
  reg signed [31:0] status_Rtri_re_0_im_3_expected;  // sfix32
  reg signed [15:0] Rtri_im_3_ref_hold;  // sfix16_En14
  wire signed [15:0] Rtri_im_3_refTmp;  // sfix16_En14
  wire signed [15:0] Rtri_im_3_ref;  // sfix16_En14
  reg  Rtri_im_3_testFailure;  // ufix1
  wire signed [15:0] Rtri_re_0_im_4_expected_1;  // sfix16_En14
  reg signed [15:0] Rtri_im_4_ref_hold;  // sfix16_En14
  wire signed [15:0] Rtri_im_4_ref;  // sfix16_En14
  reg  Rtri_im_4_testFailure;  // ufix1
  reg signed [31:0] fp_Rtri_re_0_im_5_expected;  // sfix32
  reg signed [15:0] Rtri_re_0_im_5_expected;  // sfix16_En14
  reg signed [31:0] status_Rtri_re_0_im_5_expected;  // sfix32
  reg signed [15:0] Rtri_im_5_ref_hold;  // sfix16_En14
  wire signed [15:0] Rtri_im_5_refTmp;  // sfix16_En14
  wire signed [15:0] Rtri_im_5_ref;  // sfix16_En14
  reg  Rtri_im_5_testFailure;  // ufix1
  reg signed [31:0] fp_Rtri_re_0_im_6_expected;  // sfix32
  reg signed [15:0] Rtri_re_0_im_6_expected;  // sfix16_En14
  reg signed [31:0] status_Rtri_re_0_im_6_expected;  // sfix32
  reg signed [15:0] Rtri_im_6_ref_hold;  // sfix16_En14
  wire signed [15:0] Rtri_im_6_refTmp;  // sfix16_En14
  wire signed [15:0] Rtri_im_6_ref;  // sfix16_En14
  reg  Rtri_im_6_testFailure;  // ufix1
  wire signed [15:0] Rtri_re_0_im_7_expected_1;  // sfix16_En14
  reg signed [15:0] Rtri_im_7_ref_hold;  // sfix16_En14
  wire signed [15:0] Rtri_im_7_ref;  // sfix16_En14
  reg  Rtri_im_7_testFailure;  // ufix1
  reg signed [31:0] fp_Rtri_re_0_im_8_expected;  // sfix32
  reg signed [15:0] Rtri_re_0_im_8_expected;  // sfix16_En14
  reg signed [31:0] status_Rtri_re_0_im_8_expected;  // sfix32
  reg signed [15:0] Rtri_im_8_ref_hold;  // sfix16_En14
  wire signed [15:0] Rtri_im_8_refTmp;  // sfix16_En14
  wire signed [15:0] Rtri_im_8_ref;  // sfix16_En14
  reg  Rtri_im_8_testFailure;  // ufix1
  wire signed [15:0] Rtri_re_0_im_9_expected_1;  // sfix16_En14
  reg signed [15:0] Rtri_im_9_ref_hold;  // sfix16_En14
  wire signed [15:0] Rtri_im_9_ref;  // sfix16_En14
  reg  Rtri_im_9_testFailure;  // ufix1
  reg [1:0] valid_chkcnt;  // ufix2
  wire valid_ignCntDone;  // ufix1
  wire valid_needToCount;  // ufix1
  wire valid_chkenb;  // ufix1
  wire valid_chkdata;  // ufix1
  wire [15:0] valid_addr_delay_1;  // ufix16
  reg signed [31:0] fp_valid_expected;  // sfix32
  reg  valid_expected;
  reg signed [31:0] status_valid_expected;  // sfix32
  reg  valid_ref_hold;
  wire valid_refTmp;
  wire valid_ref;
  reg  valid_testFailure;  // ufix1
  reg  testFailure;  // ufix1


  assign valid_done_enb = valid_done & ce_out;

  assign valid_lastAddr = Rtri_re_0_addr >= 16'b1111000000000001;

  assign valid_done = valid_lastAddr & resetn;

  // Delay to allow last sim cycle to complete
  always @(posedge clk or posedge reset)
    begin : checkDone_2
      if (reset) begin
        check2_done <= 0;
      end
      else begin
        if (valid_done_enb) begin
          check2_done <= valid_done;
        end
      end
    end

  assign Rtri_re_0_done_enb = Rtri_re_0_done & ce_out;

  assign Rtri_re_0_active = Rtri_re_0_addr != 16'b1111000000000001;

  assign #1 frame_start_addr_delay_1 = samp_re_addr;

  // Data source for frame_start
  initial
    begin : frame_start_fileread
      fp_frame_start = $fopen("frame_start.dat", "r");
      status_frame_start = $rewind(fp_frame_start);
    end

  always @(frame_start_addr_delay_1, phase_1, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_frame_start <= 1'bx;
      end
      else if (phase_1 == 1) begin
        status_frame_start = $fscanf(fp_frame_start, "%h", rawData_frame_start);
      end
    end

  // holdData reg for frame_start
  always @(posedge clk or posedge reset)
    begin : stimuli_frame_start
      if (reset) begin
        holdData_frame_start <= 1'bx;
      end
      else begin
        holdData_frame_start <= rawData_frame_start;
      end
    end

  always @(rawData_frame_start or phase_1)
    begin : stimuli_frame_start_1
      if (phase_1 == 1'b0) begin
        frame_start_offset <= holdData_frame_start;
      end
      else begin
        frame_start_offset <= rawData_frame_start;
      end
    end

  assign #2 frame_start = frame_start_offset;

  assign #1 samp_valid_addr_delay_1 = samp_re_addr;

  // Data source for samp_valid
  initial
    begin : samp_valid_fileread
      fp_samp_valid = $fopen("samp_valid.dat", "r");
      status_samp_valid = $rewind(fp_samp_valid);
    end

  always @(samp_valid_addr_delay_1, phase_1, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_samp_valid <= 1'bx;
      end
      else if (phase_1 == 1) begin
        status_samp_valid = $fscanf(fp_samp_valid, "%h", rawData_samp_valid);
      end
    end

  // holdData reg for samp_valid
  always @(posedge clk or posedge reset)
    begin : stimuli_samp_valid
      if (reset) begin
        holdData_samp_valid <= 1'bx;
      end
      else begin
        holdData_samp_valid <= rawData_samp_valid;
      end
    end

  always @(rawData_samp_valid or phase_1)
    begin : stimuli_samp_valid_1
      if (phase_1 == 1'b0) begin
        samp_valid_offset <= holdData_samp_valid;
      end
      else begin
        samp_valid_offset <= rawData_samp_valid;
      end
    end

  assign #2 samp_valid = samp_valid_offset;

  assign #1 samp_im_addr_delay_1 = samp_re_addr;

  // Data source for samp_im
  initial
    begin : samp_im_fileread
      fp_samp_im = $fopen("samp_im.dat", "r");
      status_samp_im = $rewind(fp_samp_im);
    end

  always @(samp_im_addr_delay_1, phase_1, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_samp_im <= 16'bx;
      end
      else if (phase_1 == 1) begin
        status_samp_im = $fscanf(fp_samp_im, "%h", rawData_samp_im);
      end
    end

  // holdData reg for samp_im
  always @(posedge clk or posedge reset)
    begin : stimuli_samp_im
      if (reset) begin
        holdData_samp_im <= 16'bx;
      end
      else begin
        holdData_samp_im <= rawData_samp_im;
      end
    end

  always @(rawData_samp_im or phase_1)
    begin : stimuli_samp_im_1
      if (phase_1 == 1'b0) begin
        samp_im_offset <= holdData_samp_im;
      end
      else begin
        samp_im_offset <= rawData_samp_im;
      end
    end

  assign #2 samp_im = samp_im_offset;

  assign samp_re_active = samp_re_addr != 16'b1111000000000001;

  assign samp_re_enb = samp_re_active & (phase_1 & tb_enb);

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 61441
  always @(posedge clk or posedge reset)
    begin : samp_re_process
      if (reset == 1'b1) begin
        samp_re_addr <= 16'b0000000000000000;
      end
      else begin
        if (samp_re_enb) begin
          if (samp_re_addr >= 16'b1111000000000001) begin
            samp_re_addr <= 16'b0000000000000000;
          end
          else begin
            samp_re_addr <= samp_re_addr + 16'b0000000000000001;
          end
        end
      end
    end

  assign #1 samp_re_addr_delay_1 = samp_re_addr;

  // Data source for samp_re
  initial
    begin : samp_re_fileread
      fp_samp_re = $fopen("samp_re.dat", "r");
      status_samp_re = $rewind(fp_samp_re);
    end

  always @(samp_re_addr_delay_1, phase_1, tb_enb)
    begin
      if (tb_enb == 0) begin
        rawData_samp_re <= 16'bx;
      end
      else if (phase_1 == 1) begin
        status_samp_re = $fscanf(fp_samp_re, "%h", rawData_samp_re);
      end
    end

  // holdData reg for samp_re
  always @(posedge clk or posedge reset)
    begin : stimuli_samp_re
      if (reset) begin
        holdData_samp_re <= 16'bx;
      end
      else begin
        holdData_samp_re <= rawData_samp_re;
      end
    end

  always @(rawData_samp_re or phase_1)
    begin : stimuli_samp_re_1
      if (phase_1 == 1'b0) begin
        samp_re_offset <= holdData_samp_re;
      end
      else begin
        samp_re_offset <= rawData_samp_re;
      end
    end

  assign #2 samp_re_1 = samp_re_offset;

  assign snkDonen =  ~ snkDone;

  assign resetn =  ~ reset;

  assign tb_enb = resetn & snkDonen;

  assign tb_enb_delay = tb_enb;

  // Count limited, Unsigned Counter
  //  initial value   = 1
  //  step value      = 1
  //  count to value  = 79
  always @(posedge clk or posedge reset)
    begin : slow_clock_enable_process
      if (reset == 1'b1) begin
        counter <= 7'b0000001;
      end
      else begin
        if (tb_enb_delay) begin
          if (counter >= 7'b1001111) begin
            counter <= 7'b0000000;
          end
          else begin
            counter <= counter + 7'b0000001;
          end
        end
      end
    end

  assign phase_1_ctr = counter == 7'b0000001;

  assign phase_1 = phase_1_ctr & tb_enb;

  assign notDone = phase_1 & snkDonen;

  assign #2 enb = notDone;

  initial
    begin : reset_gen
      reset <= 1'b1;
      # (20);
      @ (posedge clk)
      # (2);
      reset <= 1'b0;
    end

  always 
    begin : clk_gen
      clk <= 1'b1;
      # (5);
      clk <= 1'b0;
      # (5);
      if (snkDone == 1'b1) begin
        clk <= 1'b1;
        # (5);
        clk <= 1'b0;
        # (5);
        $stop;
      end
    end

  covariance_core_fixpt u_covariance_core_fixpt (.clk(clk),
                                                 .reset(reset),
                                                 .clk_enable(enb),
                                                 .samp_re(samp_re_1),  // sfix16_En13
                                                 .samp_im(samp_im),  // sfix16_En13
                                                 .samp_valid(samp_valid),
                                                 .frame_start(frame_start),
                                                 .ce_out(ce_out),
                                                 .Rtri_re_0(Rtri_re_0),  // sfix16_En14
                                                 .Rtri_re_1(Rtri_re_1),  // sfix16_En14
                                                 .Rtri_re_2(Rtri_re_2),  // sfix16_En14
                                                 .Rtri_re_3(Rtri_re_3),  // sfix16_En14
                                                 .Rtri_re_4(Rtri_re_4),  // sfix16_En14
                                                 .Rtri_re_5(Rtri_re_5),  // sfix16_En14
                                                 .Rtri_re_6(Rtri_re_6),  // sfix16_En14
                                                 .Rtri_re_7(Rtri_re_7),  // sfix16_En14
                                                 .Rtri_re_8(Rtri_re_8),  // sfix16_En14
                                                 .Rtri_re_9(Rtri_re_9),  // sfix16_En14
                                                 .Rtri_im_0(Rtri_im_0),  // sfix16_En14
                                                 .Rtri_im_1(Rtri_im_1),  // sfix16_En14
                                                 .Rtri_im_2(Rtri_im_2),  // sfix16_En14
                                                 .Rtri_im_3(Rtri_im_3),  // sfix16_En14
                                                 .Rtri_im_4(Rtri_im_4),  // sfix16_En14
                                                 .Rtri_im_5(Rtri_im_5),  // sfix16_En14
                                                 .Rtri_im_6(Rtri_im_6),  // sfix16_En14
                                                 .Rtri_im_7(Rtri_im_7),  // sfix16_En14
                                                 .Rtri_im_8(Rtri_im_8),  // sfix16_En14
                                                 .Rtri_im_9(Rtri_im_9),  // sfix16_En14
                                                 .valid(valid)
                                                 );

  assign Rtri_re_0_enb = ce_out & Rtri_re_0_active;

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 61441
  always @(posedge clk or posedge reset)
    begin : Rtri_process
      if (reset == 1'b1) begin
        Rtri_re_0_addr <= 16'b0000000000000000;
      end
      else begin
        if (Rtri_re_0_enb) begin
          if (Rtri_re_0_addr >= 16'b1111000000000001) begin
            Rtri_re_0_addr <= 16'b0000000000000000;
          end
          else begin
            Rtri_re_0_addr <= Rtri_re_0_addr + 16'b0000000000000001;
          end
        end
      end
    end

  assign Rtri_re_0_lastAddr = Rtri_re_0_addr >= 16'b1111000000000001;

  assign Rtri_re_0_done = Rtri_re_0_lastAddr & resetn;

  // Delay to allow last sim cycle to complete
  always @(posedge clk or posedge reset)
    begin : checkDone_1
      if (reset) begin
        check1_done <= 0;
      end
      else begin
        if (Rtri_re_0_done_enb) begin
          check1_done <= Rtri_re_0_done;
        end
      end
    end

  assign snkDone = check1_done & check2_done;

  assign Rtri_re_0_ignCntDone = Rtri_re_0_chkcnt != 2'b10;

  assign Rtri_re_0_needToCount = ce_out & Rtri_re_0_ignCntDone;

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 2
  always @(posedge clk or posedge reset)
    begin : Rtri_re_0_IgnoreDataChecking_process
      if (reset == 1'b1) begin
        Rtri_re_0_chkcnt <= 2'b00;
      end
      else begin
        if (Rtri_re_0_needToCount) begin
          if (Rtri_re_0_chkcnt >= 2'b10) begin
            Rtri_re_0_chkcnt <= 2'b00;
          end
          else begin
            Rtri_re_0_chkcnt <= Rtri_re_0_chkcnt + 2'b01;
          end
        end
      end
    end

  assign Rtri_re_0_chkenb = Rtri_re_0_chkcnt == 2'b10;

  assign Rtri_re_0_chkdata = ce_out & Rtri_re_0_chkenb;

  assign #1 Rtri_re_0_addr_delay_1 = Rtri_re_0_addr;

  // Data source for Rtri_re_0_re_0_expected
  initial
    begin : Rtri_re_0_re_0_expected_fileread
      fp_Rtri_re_0_re_0_expected = $fopen("Rtri_re_0_re_0_expected.dat", "r");
      status_Rtri_re_0_re_0_expected = $rewind(fp_Rtri_re_0_re_0_expected);
    end

  always @(Rtri_re_0_addr_delay_1,  tb_enb)
    begin
      if (tb_enb == 0) begin
        Rtri_re_0_re_0_expected <= 16'bx;
      end
      else  begin
        status_Rtri_re_0_re_0_expected = $fscanf(fp_Rtri_re_0_re_0_expected, "%h", Rtri_re_0_re_0_expected);
      end
    end

  // Bypass register to hold Rtri_re_0_ref
  always @(posedge clk or posedge reset)
    begin : DataHold_Rtri_re_0_ref
      if (reset) begin
        Rtri_re_0_ref_hold <= 0;
      end
      else begin
        if (ce_out) begin
          Rtri_re_0_ref_hold <= Rtri_re_0_re_0_expected;
        end
      end
    end

  assign Rtri_re_0_refTmp = Rtri_re_0_re_0_expected;

  assign Rtri_re_0_ref = (ce_out == 1'b0 ? Rtri_re_0_ref_hold :
              Rtri_re_0_refTmp);

  always @(posedge clk or posedge reset)
    begin : Rtri_re_0_checker
      if (reset == 1'b1) begin
        Rtri_re_0_testFailure <= 1'b0;
      end
      else begin
        if (Rtri_re_0_chkdata == 1'b1 && Rtri_re_0 !== Rtri_re_0_ref) begin
          Rtri_re_0_testFailure <= 1'b1;
          $display("ERROR in Rtri_re_0 at time %t : Expected '%h' Actual '%h'", $time, Rtri_re_0_ref, Rtri_re_0);
        end
      end
    end

  // Data source for Rtri_re_0_re_1_expected
  initial
    begin : Rtri_re_0_re_1_expected_fileread
      fp_Rtri_re_0_re_1_expected = $fopen("Rtri_re_0_re_1_expected.dat", "r");
      status_Rtri_re_0_re_1_expected = $rewind(fp_Rtri_re_0_re_1_expected);
    end

  always @(Rtri_re_0_addr_delay_1,  tb_enb)
    begin
      if (tb_enb == 0) begin
        Rtri_re_0_re_1_expected <= 16'bx;
      end
      else  begin
        status_Rtri_re_0_re_1_expected = $fscanf(fp_Rtri_re_0_re_1_expected, "%h", Rtri_re_0_re_1_expected);
      end
    end

  // Bypass register to hold Rtri_re_1_ref
  always @(posedge clk or posedge reset)
    begin : DataHold_Rtri_re_1_ref
      if (reset) begin
        Rtri_re_1_ref_hold <= 0;
      end
      else begin
        if (ce_out) begin
          Rtri_re_1_ref_hold <= Rtri_re_0_re_1_expected;
        end
      end
    end

  assign Rtri_re_1_refTmp = Rtri_re_0_re_1_expected;

  assign Rtri_re_1_ref = (ce_out == 1'b0 ? Rtri_re_1_ref_hold :
              Rtri_re_1_refTmp);

  always @(posedge clk or posedge reset)
    begin : Rtri_re_1_checker
      if (reset == 1'b1) begin
        Rtri_re_1_testFailure <= 1'b0;
      end
      else begin
        if (Rtri_re_0_chkdata == 1'b1 && Rtri_re_1 !== Rtri_re_1_ref) begin
          Rtri_re_1_testFailure <= 1'b1;
          $display("ERROR in Rtri_re_1 at time %t : Expected '%h' Actual '%h'", $time, Rtri_re_1_ref, Rtri_re_1);
        end
      end
    end

  // Data source for Rtri_re_0_re_2_expected
  initial
    begin : Rtri_re_0_re_2_expected_fileread
      fp_Rtri_re_0_re_2_expected = $fopen("Rtri_re_0_re_2_expected.dat", "r");
      status_Rtri_re_0_re_2_expected = $rewind(fp_Rtri_re_0_re_2_expected);
    end

  always @(Rtri_re_0_addr_delay_1,  tb_enb)
    begin
      if (tb_enb == 0) begin
        Rtri_re_0_re_2_expected <= 16'bx;
      end
      else  begin
        status_Rtri_re_0_re_2_expected = $fscanf(fp_Rtri_re_0_re_2_expected, "%h", Rtri_re_0_re_2_expected);
      end
    end

  // Bypass register to hold Rtri_re_2_ref
  always @(posedge clk or posedge reset)
    begin : DataHold_Rtri_re_2_ref
      if (reset) begin
        Rtri_re_2_ref_hold <= 0;
      end
      else begin
        if (ce_out) begin
          Rtri_re_2_ref_hold <= Rtri_re_0_re_2_expected;
        end
      end
    end

  assign Rtri_re_2_refTmp = Rtri_re_0_re_2_expected;

  assign Rtri_re_2_ref = (ce_out == 1'b0 ? Rtri_re_2_ref_hold :
              Rtri_re_2_refTmp);

  always @(posedge clk or posedge reset)
    begin : Rtri_re_2_checker
      if (reset == 1'b1) begin
        Rtri_re_2_testFailure <= 1'b0;
      end
      else begin
        if (Rtri_re_0_chkdata == 1'b1 && Rtri_re_2 !== Rtri_re_2_ref) begin
          Rtri_re_2_testFailure <= 1'b1;
          $display("ERROR in Rtri_re_2 at time %t : Expected '%h' Actual '%h'", $time, Rtri_re_2_ref, Rtri_re_2);
        end
      end
    end

  // Data source for Rtri_re_0_re_3_expected
  initial
    begin : Rtri_re_0_re_3_expected_fileread
      fp_Rtri_re_0_re_3_expected = $fopen("Rtri_re_0_re_3_expected.dat", "r");
      status_Rtri_re_0_re_3_expected = $rewind(fp_Rtri_re_0_re_3_expected);
    end

  always @(Rtri_re_0_addr_delay_1,  tb_enb)
    begin
      if (tb_enb == 0) begin
        Rtri_re_0_re_3_expected <= 16'bx;
      end
      else  begin
        status_Rtri_re_0_re_3_expected = $fscanf(fp_Rtri_re_0_re_3_expected, "%h", Rtri_re_0_re_3_expected);
      end
    end

  // Bypass register to hold Rtri_re_3_ref
  always @(posedge clk or posedge reset)
    begin : DataHold_Rtri_re_3_ref
      if (reset) begin
        Rtri_re_3_ref_hold <= 0;
      end
      else begin
        if (ce_out) begin
          Rtri_re_3_ref_hold <= Rtri_re_0_re_3_expected;
        end
      end
    end

  assign Rtri_re_3_refTmp = Rtri_re_0_re_3_expected;

  assign Rtri_re_3_ref = (ce_out == 1'b0 ? Rtri_re_3_ref_hold :
              Rtri_re_3_refTmp);

  always @(posedge clk or posedge reset)
    begin : Rtri_re_3_checker
      if (reset == 1'b1) begin
        Rtri_re_3_testFailure <= 1'b0;
      end
      else begin
        if (Rtri_re_0_chkdata == 1'b1 && Rtri_re_3 !== Rtri_re_3_ref) begin
          Rtri_re_3_testFailure <= 1'b1;
          $display("ERROR in Rtri_re_3 at time %t : Expected '%h' Actual '%h'", $time, Rtri_re_3_ref, Rtri_re_3);
        end
      end
    end

  // Data source for Rtri_re_0_re_4_expected
  initial
    begin : Rtri_re_0_re_4_expected_fileread
      fp_Rtri_re_0_re_4_expected = $fopen("Rtri_re_0_re_4_expected.dat", "r");
      status_Rtri_re_0_re_4_expected = $rewind(fp_Rtri_re_0_re_4_expected);
    end

  always @(Rtri_re_0_addr_delay_1,  tb_enb)
    begin
      if (tb_enb == 0) begin
        Rtri_re_0_re_4_expected <= 16'bx;
      end
      else  begin
        status_Rtri_re_0_re_4_expected = $fscanf(fp_Rtri_re_0_re_4_expected, "%h", Rtri_re_0_re_4_expected);
      end
    end

  // Bypass register to hold Rtri_re_4_ref
  always @(posedge clk or posedge reset)
    begin : DataHold_Rtri_re_4_ref
      if (reset) begin
        Rtri_re_4_ref_hold <= 0;
      end
      else begin
        if (ce_out) begin
          Rtri_re_4_ref_hold <= Rtri_re_0_re_4_expected;
        end
      end
    end

  assign Rtri_re_4_refTmp = Rtri_re_0_re_4_expected;

  assign Rtri_re_4_ref = (ce_out == 1'b0 ? Rtri_re_4_ref_hold :
              Rtri_re_4_refTmp);

  always @(posedge clk or posedge reset)
    begin : Rtri_re_4_checker
      if (reset == 1'b1) begin
        Rtri_re_4_testFailure <= 1'b0;
      end
      else begin
        if (Rtri_re_0_chkdata == 1'b1 && Rtri_re_4 !== Rtri_re_4_ref) begin
          Rtri_re_4_testFailure <= 1'b1;
          $display("ERROR in Rtri_re_4 at time %t : Expected '%h' Actual '%h'", $time, Rtri_re_4_ref, Rtri_re_4);
        end
      end
    end

  // Data source for Rtri_re_0_re_5_expected
  initial
    begin : Rtri_re_0_re_5_expected_fileread
      fp_Rtri_re_0_re_5_expected = $fopen("Rtri_re_0_re_5_expected.dat", "r");
      status_Rtri_re_0_re_5_expected = $rewind(fp_Rtri_re_0_re_5_expected);
    end

  always @(Rtri_re_0_addr_delay_1,  tb_enb)
    begin
      if (tb_enb == 0) begin
        Rtri_re_0_re_5_expected <= 16'bx;
      end
      else  begin
        status_Rtri_re_0_re_5_expected = $fscanf(fp_Rtri_re_0_re_5_expected, "%h", Rtri_re_0_re_5_expected);
      end
    end

  // Bypass register to hold Rtri_re_5_ref
  always @(posedge clk or posedge reset)
    begin : DataHold_Rtri_re_5_ref
      if (reset) begin
        Rtri_re_5_ref_hold <= 0;
      end
      else begin
        if (ce_out) begin
          Rtri_re_5_ref_hold <= Rtri_re_0_re_5_expected;
        end
      end
    end

  assign Rtri_re_5_refTmp = Rtri_re_0_re_5_expected;

  assign Rtri_re_5_ref = (ce_out == 1'b0 ? Rtri_re_5_ref_hold :
              Rtri_re_5_refTmp);

  always @(posedge clk or posedge reset)
    begin : Rtri_re_5_checker
      if (reset == 1'b1) begin
        Rtri_re_5_testFailure <= 1'b0;
      end
      else begin
        if (Rtri_re_0_chkdata == 1'b1 && Rtri_re_5 !== Rtri_re_5_ref) begin
          Rtri_re_5_testFailure <= 1'b1;
          $display("ERROR in Rtri_re_5 at time %t : Expected '%h' Actual '%h'", $time, Rtri_re_5_ref, Rtri_re_5);
        end
      end
    end

  // Data source for Rtri_re_0_re_6_expected
  initial
    begin : Rtri_re_0_re_6_expected_fileread
      fp_Rtri_re_0_re_6_expected = $fopen("Rtri_re_0_re_6_expected.dat", "r");
      status_Rtri_re_0_re_6_expected = $rewind(fp_Rtri_re_0_re_6_expected);
    end

  always @(Rtri_re_0_addr_delay_1,  tb_enb)
    begin
      if (tb_enb == 0) begin
        Rtri_re_0_re_6_expected <= 16'bx;
      end
      else  begin
        status_Rtri_re_0_re_6_expected = $fscanf(fp_Rtri_re_0_re_6_expected, "%h", Rtri_re_0_re_6_expected);
      end
    end

  // Bypass register to hold Rtri_re_6_ref
  always @(posedge clk or posedge reset)
    begin : DataHold_Rtri_re_6_ref
      if (reset) begin
        Rtri_re_6_ref_hold <= 0;
      end
      else begin
        if (ce_out) begin
          Rtri_re_6_ref_hold <= Rtri_re_0_re_6_expected;
        end
      end
    end

  assign Rtri_re_6_refTmp = Rtri_re_0_re_6_expected;

  assign Rtri_re_6_ref = (ce_out == 1'b0 ? Rtri_re_6_ref_hold :
              Rtri_re_6_refTmp);

  always @(posedge clk or posedge reset)
    begin : Rtri_re_6_checker
      if (reset == 1'b1) begin
        Rtri_re_6_testFailure <= 1'b0;
      end
      else begin
        if (Rtri_re_0_chkdata == 1'b1 && Rtri_re_6 !== Rtri_re_6_ref) begin
          Rtri_re_6_testFailure <= 1'b1;
          $display("ERROR in Rtri_re_6 at time %t : Expected '%h' Actual '%h'", $time, Rtri_re_6_ref, Rtri_re_6);
        end
      end
    end

  // Data source for Rtri_re_0_re_7_expected
  initial
    begin : Rtri_re_0_re_7_expected_fileread
      fp_Rtri_re_0_re_7_expected = $fopen("Rtri_re_0_re_7_expected.dat", "r");
      status_Rtri_re_0_re_7_expected = $rewind(fp_Rtri_re_0_re_7_expected);
    end

  always @(Rtri_re_0_addr_delay_1,  tb_enb)
    begin
      if (tb_enb == 0) begin
        Rtri_re_0_re_7_expected <= 16'bx;
      end
      else  begin
        status_Rtri_re_0_re_7_expected = $fscanf(fp_Rtri_re_0_re_7_expected, "%h", Rtri_re_0_re_7_expected);
      end
    end

  // Bypass register to hold Rtri_re_7_ref
  always @(posedge clk or posedge reset)
    begin : DataHold_Rtri_re_7_ref
      if (reset) begin
        Rtri_re_7_ref_hold <= 0;
      end
      else begin
        if (ce_out) begin
          Rtri_re_7_ref_hold <= Rtri_re_0_re_7_expected;
        end
      end
    end

  assign Rtri_re_7_refTmp = Rtri_re_0_re_7_expected;

  assign Rtri_re_7_ref = (ce_out == 1'b0 ? Rtri_re_7_ref_hold :
              Rtri_re_7_refTmp);

  always @(posedge clk or posedge reset)
    begin : Rtri_re_7_checker
      if (reset == 1'b1) begin
        Rtri_re_7_testFailure <= 1'b0;
      end
      else begin
        if (Rtri_re_0_chkdata == 1'b1 && Rtri_re_7 !== Rtri_re_7_ref) begin
          Rtri_re_7_testFailure <= 1'b1;
          $display("ERROR in Rtri_re_7 at time %t : Expected '%h' Actual '%h'", $time, Rtri_re_7_ref, Rtri_re_7);
        end
      end
    end

  // Data source for Rtri_re_0_re_8_expected
  initial
    begin : Rtri_re_0_re_8_expected_fileread
      fp_Rtri_re_0_re_8_expected = $fopen("Rtri_re_0_re_8_expected.dat", "r");
      status_Rtri_re_0_re_8_expected = $rewind(fp_Rtri_re_0_re_8_expected);
    end

  always @(Rtri_re_0_addr_delay_1,  tb_enb)
    begin
      if (tb_enb == 0) begin
        Rtri_re_0_re_8_expected <= 16'bx;
      end
      else  begin
        status_Rtri_re_0_re_8_expected = $fscanf(fp_Rtri_re_0_re_8_expected, "%h", Rtri_re_0_re_8_expected);
      end
    end

  // Bypass register to hold Rtri_re_8_ref
  always @(posedge clk or posedge reset)
    begin : DataHold_Rtri_re_8_ref
      if (reset) begin
        Rtri_re_8_ref_hold <= 0;
      end
      else begin
        if (ce_out) begin
          Rtri_re_8_ref_hold <= Rtri_re_0_re_8_expected;
        end
      end
    end

  assign Rtri_re_8_refTmp = Rtri_re_0_re_8_expected;

  assign Rtri_re_8_ref = (ce_out == 1'b0 ? Rtri_re_8_ref_hold :
              Rtri_re_8_refTmp);

  always @(posedge clk or posedge reset)
    begin : Rtri_re_8_checker
      if (reset == 1'b1) begin
        Rtri_re_8_testFailure <= 1'b0;
      end
      else begin
        if (Rtri_re_0_chkdata == 1'b1 && Rtri_re_8 !== Rtri_re_8_ref) begin
          Rtri_re_8_testFailure <= 1'b1;
          $display("ERROR in Rtri_re_8 at time %t : Expected '%h' Actual '%h'", $time, Rtri_re_8_ref, Rtri_re_8);
        end
      end
    end

  // Data source for Rtri_re_0_re_9_expected
  initial
    begin : Rtri_re_0_re_9_expected_fileread
      fp_Rtri_re_0_re_9_expected = $fopen("Rtri_re_0_re_9_expected.dat", "r");
      status_Rtri_re_0_re_9_expected = $rewind(fp_Rtri_re_0_re_9_expected);
    end

  always @(Rtri_re_0_addr_delay_1,  tb_enb)
    begin
      if (tb_enb == 0) begin
        Rtri_re_0_re_9_expected <= 16'bx;
      end
      else  begin
        status_Rtri_re_0_re_9_expected = $fscanf(fp_Rtri_re_0_re_9_expected, "%h", Rtri_re_0_re_9_expected);
      end
    end

  // Bypass register to hold Rtri_re_9_ref
  always @(posedge clk or posedge reset)
    begin : DataHold_Rtri_re_9_ref
      if (reset) begin
        Rtri_re_9_ref_hold <= 0;
      end
      else begin
        if (ce_out) begin
          Rtri_re_9_ref_hold <= Rtri_re_0_re_9_expected;
        end
      end
    end

  assign Rtri_re_9_refTmp = Rtri_re_0_re_9_expected;

  assign Rtri_re_9_ref = (ce_out == 1'b0 ? Rtri_re_9_ref_hold :
              Rtri_re_9_refTmp);

  always @(posedge clk or posedge reset)
    begin : Rtri_re_9_checker
      if (reset == 1'b1) begin
        Rtri_re_9_testFailure <= 1'b0;
      end
      else begin
        if (Rtri_re_0_chkdata == 1'b1 && Rtri_re_9 !== Rtri_re_9_ref) begin
          Rtri_re_9_testFailure <= 1'b1;
          $display("ERROR in Rtri_re_9 at time %t : Expected '%h' Actual '%h'", $time, Rtri_re_9_ref, Rtri_re_9);
        end
      end
    end

  // Data source for Rtri_re_0_im_0_expected
  assign Rtri_re_0_im_0_expected_1 = 16'sb0000000000000000;

  // Bypass register to hold Rtri_im_0_ref
  always @(posedge clk or posedge reset)
    begin : DataHold_Rtri_im_0_ref
      if (reset) begin
        Rtri_im_0_ref_hold <= 0;
      end
      else begin
        if (ce_out) begin
          Rtri_im_0_ref_hold <= Rtri_re_0_im_0_expected_1;
        end
      end
    end

  // Data source for Rtri_re_0_im_0_expected
  assign Rtri_im_0_ref = (ce_out == 1'b0 ? Rtri_im_0_ref_hold :
              16'sb0000000000000000);

  always @(posedge clk or posedge reset)
    begin : Rtri_im_0_checker
      if (reset == 1'b1) begin
        Rtri_im_0_testFailure <= 1'b0;
      end
      else begin
        if (Rtri_re_0_chkdata == 1'b1 && Rtri_im_0 !== Rtri_im_0_ref) begin
          Rtri_im_0_testFailure <= 1'b1;
          $display("ERROR in Rtri_im_0 at time %t : Expected '%h' Actual '%h'", $time, Rtri_im_0_ref, Rtri_im_0);
        end
      end
    end

  // Data source for Rtri_re_0_im_1_expected
  initial
    begin : Rtri_re_0_im_1_expected_fileread
      fp_Rtri_re_0_im_1_expected = $fopen("Rtri_re_0_im_1_expected.dat", "r");
      status_Rtri_re_0_im_1_expected = $rewind(fp_Rtri_re_0_im_1_expected);
    end

  always @(Rtri_re_0_addr_delay_1,  tb_enb)
    begin
      if (tb_enb == 0) begin
        Rtri_re_0_im_1_expected <= 16'bx;
      end
      else  begin
        status_Rtri_re_0_im_1_expected = $fscanf(fp_Rtri_re_0_im_1_expected, "%h", Rtri_re_0_im_1_expected);
      end
    end

  // Bypass register to hold Rtri_im_1_ref
  always @(posedge clk or posedge reset)
    begin : DataHold_Rtri_im_1_ref
      if (reset) begin
        Rtri_im_1_ref_hold <= 0;
      end
      else begin
        if (ce_out) begin
          Rtri_im_1_ref_hold <= Rtri_re_0_im_1_expected;
        end
      end
    end

  assign Rtri_im_1_refTmp = Rtri_re_0_im_1_expected;

  assign Rtri_im_1_ref = (ce_out == 1'b0 ? Rtri_im_1_ref_hold :
              Rtri_im_1_refTmp);

  always @(posedge clk or posedge reset)
    begin : Rtri_im_1_checker
      if (reset == 1'b1) begin
        Rtri_im_1_testFailure <= 1'b0;
      end
      else begin
        if (Rtri_re_0_chkdata == 1'b1 && Rtri_im_1 !== Rtri_im_1_ref) begin
          Rtri_im_1_testFailure <= 1'b1;
          $display("ERROR in Rtri_im_1 at time %t : Expected '%h' Actual '%h'", $time, Rtri_im_1_ref, Rtri_im_1);
        end
      end
    end

  // Data source for Rtri_re_0_im_2_expected
  initial
    begin : Rtri_re_0_im_2_expected_fileread
      fp_Rtri_re_0_im_2_expected = $fopen("Rtri_re_0_im_2_expected.dat", "r");
      status_Rtri_re_0_im_2_expected = $rewind(fp_Rtri_re_0_im_2_expected);
    end

  always @(Rtri_re_0_addr_delay_1,  tb_enb)
    begin
      if (tb_enb == 0) begin
        Rtri_re_0_im_2_expected <= 16'bx;
      end
      else  begin
        status_Rtri_re_0_im_2_expected = $fscanf(fp_Rtri_re_0_im_2_expected, "%h", Rtri_re_0_im_2_expected);
      end
    end

  // Bypass register to hold Rtri_im_2_ref
  always @(posedge clk or posedge reset)
    begin : DataHold_Rtri_im_2_ref
      if (reset) begin
        Rtri_im_2_ref_hold <= 0;
      end
      else begin
        if (ce_out) begin
          Rtri_im_2_ref_hold <= Rtri_re_0_im_2_expected;
        end
      end
    end

  assign Rtri_im_2_refTmp = Rtri_re_0_im_2_expected;

  assign Rtri_im_2_ref = (ce_out == 1'b0 ? Rtri_im_2_ref_hold :
              Rtri_im_2_refTmp);

  always @(posedge clk or posedge reset)
    begin : Rtri_im_2_checker
      if (reset == 1'b1) begin
        Rtri_im_2_testFailure <= 1'b0;
      end
      else begin
        if (Rtri_re_0_chkdata == 1'b1 && Rtri_im_2 !== Rtri_im_2_ref) begin
          Rtri_im_2_testFailure <= 1'b1;
          $display("ERROR in Rtri_im_2 at time %t : Expected '%h' Actual '%h'", $time, Rtri_im_2_ref, Rtri_im_2);
        end
      end
    end

  // Data source for Rtri_re_0_im_3_expected
  initial
    begin : Rtri_re_0_im_3_expected_fileread
      fp_Rtri_re_0_im_3_expected = $fopen("Rtri_re_0_im_3_expected.dat", "r");
      status_Rtri_re_0_im_3_expected = $rewind(fp_Rtri_re_0_im_3_expected);
    end

  always @(Rtri_re_0_addr_delay_1,  tb_enb)
    begin
      if (tb_enb == 0) begin
        Rtri_re_0_im_3_expected <= 16'bx;
      end
      else  begin
        status_Rtri_re_0_im_3_expected = $fscanf(fp_Rtri_re_0_im_3_expected, "%h", Rtri_re_0_im_3_expected);
      end
    end

  // Bypass register to hold Rtri_im_3_ref
  always @(posedge clk or posedge reset)
    begin : DataHold_Rtri_im_3_ref
      if (reset) begin
        Rtri_im_3_ref_hold <= 0;
      end
      else begin
        if (ce_out) begin
          Rtri_im_3_ref_hold <= Rtri_re_0_im_3_expected;
        end
      end
    end

  assign Rtri_im_3_refTmp = Rtri_re_0_im_3_expected;

  assign Rtri_im_3_ref = (ce_out == 1'b0 ? Rtri_im_3_ref_hold :
              Rtri_im_3_refTmp);

  always @(posedge clk or posedge reset)
    begin : Rtri_im_3_checker
      if (reset == 1'b1) begin
        Rtri_im_3_testFailure <= 1'b0;
      end
      else begin
        if (Rtri_re_0_chkdata == 1'b1 && Rtri_im_3 !== Rtri_im_3_ref) begin
          Rtri_im_3_testFailure <= 1'b1;
          $display("ERROR in Rtri_im_3 at time %t : Expected '%h' Actual '%h'", $time, Rtri_im_3_ref, Rtri_im_3);
        end
      end
    end

  // Data source for Rtri_re_0_im_4_expected
  assign Rtri_re_0_im_4_expected_1 = 16'sb0000000000000000;

  // Bypass register to hold Rtri_im_4_ref
  always @(posedge clk or posedge reset)
    begin : DataHold_Rtri_im_4_ref
      if (reset) begin
        Rtri_im_4_ref_hold <= 0;
      end
      else begin
        if (ce_out) begin
          Rtri_im_4_ref_hold <= Rtri_re_0_im_4_expected_1;
        end
      end
    end

  // Data source for Rtri_re_0_im_4_expected
  assign Rtri_im_4_ref = (ce_out == 1'b0 ? Rtri_im_4_ref_hold :
              16'sb0000000000000000);

  always @(posedge clk or posedge reset)
    begin : Rtri_im_4_checker
      if (reset == 1'b1) begin
        Rtri_im_4_testFailure <= 1'b0;
      end
      else begin
        if (Rtri_re_0_chkdata == 1'b1 && Rtri_im_4 !== Rtri_im_4_ref) begin
          Rtri_im_4_testFailure <= 1'b1;
          $display("ERROR in Rtri_im_4 at time %t : Expected '%h' Actual '%h'", $time, Rtri_im_4_ref, Rtri_im_4);
        end
      end
    end

  // Data source for Rtri_re_0_im_5_expected
  initial
    begin : Rtri_re_0_im_5_expected_fileread
      fp_Rtri_re_0_im_5_expected = $fopen("Rtri_re_0_im_5_expected.dat", "r");
      status_Rtri_re_0_im_5_expected = $rewind(fp_Rtri_re_0_im_5_expected);
    end

  always @(Rtri_re_0_addr_delay_1,  tb_enb)
    begin
      if (tb_enb == 0) begin
        Rtri_re_0_im_5_expected <= 16'bx;
      end
      else  begin
        status_Rtri_re_0_im_5_expected = $fscanf(fp_Rtri_re_0_im_5_expected, "%h", Rtri_re_0_im_5_expected);
      end
    end

  // Bypass register to hold Rtri_im_5_ref
  always @(posedge clk or posedge reset)
    begin : DataHold_Rtri_im_5_ref
      if (reset) begin
        Rtri_im_5_ref_hold <= 0;
      end
      else begin
        if (ce_out) begin
          Rtri_im_5_ref_hold <= Rtri_re_0_im_5_expected;
        end
      end
    end

  assign Rtri_im_5_refTmp = Rtri_re_0_im_5_expected;

  assign Rtri_im_5_ref = (ce_out == 1'b0 ? Rtri_im_5_ref_hold :
              Rtri_im_5_refTmp);

  always @(posedge clk or posedge reset)
    begin : Rtri_im_5_checker
      if (reset == 1'b1) begin
        Rtri_im_5_testFailure <= 1'b0;
      end
      else begin
        if (Rtri_re_0_chkdata == 1'b1 && Rtri_im_5 !== Rtri_im_5_ref) begin
          Rtri_im_5_testFailure <= 1'b1;
          $display("ERROR in Rtri_im_5 at time %t : Expected '%h' Actual '%h'", $time, Rtri_im_5_ref, Rtri_im_5);
        end
      end
    end

  // Data source for Rtri_re_0_im_6_expected
  initial
    begin : Rtri_re_0_im_6_expected_fileread
      fp_Rtri_re_0_im_6_expected = $fopen("Rtri_re_0_im_6_expected.dat", "r");
      status_Rtri_re_0_im_6_expected = $rewind(fp_Rtri_re_0_im_6_expected);
    end

  always @(Rtri_re_0_addr_delay_1,  tb_enb)
    begin
      if (tb_enb == 0) begin
        Rtri_re_0_im_6_expected <= 16'bx;
      end
      else  begin
        status_Rtri_re_0_im_6_expected = $fscanf(fp_Rtri_re_0_im_6_expected, "%h", Rtri_re_0_im_6_expected);
      end
    end

  // Bypass register to hold Rtri_im_6_ref
  always @(posedge clk or posedge reset)
    begin : DataHold_Rtri_im_6_ref
      if (reset) begin
        Rtri_im_6_ref_hold <= 0;
      end
      else begin
        if (ce_out) begin
          Rtri_im_6_ref_hold <= Rtri_re_0_im_6_expected;
        end
      end
    end

  assign Rtri_im_6_refTmp = Rtri_re_0_im_6_expected;

  assign Rtri_im_6_ref = (ce_out == 1'b0 ? Rtri_im_6_ref_hold :
              Rtri_im_6_refTmp);

  always @(posedge clk or posedge reset)
    begin : Rtri_im_6_checker
      if (reset == 1'b1) begin
        Rtri_im_6_testFailure <= 1'b0;
      end
      else begin
        if (Rtri_re_0_chkdata == 1'b1 && Rtri_im_6 !== Rtri_im_6_ref) begin
          Rtri_im_6_testFailure <= 1'b1;
          $display("ERROR in Rtri_im_6 at time %t : Expected '%h' Actual '%h'", $time, Rtri_im_6_ref, Rtri_im_6);
        end
      end
    end

  // Data source for Rtri_re_0_im_7_expected
  assign Rtri_re_0_im_7_expected_1 = 16'sb0000000000000000;

  // Bypass register to hold Rtri_im_7_ref
  always @(posedge clk or posedge reset)
    begin : DataHold_Rtri_im_7_ref
      if (reset) begin
        Rtri_im_7_ref_hold <= 0;
      end
      else begin
        if (ce_out) begin
          Rtri_im_7_ref_hold <= Rtri_re_0_im_7_expected_1;
        end
      end
    end

  // Data source for Rtri_re_0_im_7_expected
  assign Rtri_im_7_ref = (ce_out == 1'b0 ? Rtri_im_7_ref_hold :
              16'sb0000000000000000);

  always @(posedge clk or posedge reset)
    begin : Rtri_im_7_checker
      if (reset == 1'b1) begin
        Rtri_im_7_testFailure <= 1'b0;
      end
      else begin
        if (Rtri_re_0_chkdata == 1'b1 && Rtri_im_7 !== Rtri_im_7_ref) begin
          Rtri_im_7_testFailure <= 1'b1;
          $display("ERROR in Rtri_im_7 at time %t : Expected '%h' Actual '%h'", $time, Rtri_im_7_ref, Rtri_im_7);
        end
      end
    end

  // Data source for Rtri_re_0_im_8_expected
  initial
    begin : Rtri_re_0_im_8_expected_fileread
      fp_Rtri_re_0_im_8_expected = $fopen("Rtri_re_0_im_8_expected.dat", "r");
      status_Rtri_re_0_im_8_expected = $rewind(fp_Rtri_re_0_im_8_expected);
    end

  always @(Rtri_re_0_addr_delay_1,  tb_enb)
    begin
      if (tb_enb == 0) begin
        Rtri_re_0_im_8_expected <= 16'bx;
      end
      else  begin
        status_Rtri_re_0_im_8_expected = $fscanf(fp_Rtri_re_0_im_8_expected, "%h", Rtri_re_0_im_8_expected);
      end
    end

  // Bypass register to hold Rtri_im_8_ref
  always @(posedge clk or posedge reset)
    begin : DataHold_Rtri_im_8_ref
      if (reset) begin
        Rtri_im_8_ref_hold <= 0;
      end
      else begin
        if (ce_out) begin
          Rtri_im_8_ref_hold <= Rtri_re_0_im_8_expected;
        end
      end
    end

  assign Rtri_im_8_refTmp = Rtri_re_0_im_8_expected;

  assign Rtri_im_8_ref = (ce_out == 1'b0 ? Rtri_im_8_ref_hold :
              Rtri_im_8_refTmp);

  always @(posedge clk or posedge reset)
    begin : Rtri_im_8_checker
      if (reset == 1'b1) begin
        Rtri_im_8_testFailure <= 1'b0;
      end
      else begin
        if (Rtri_re_0_chkdata == 1'b1 && Rtri_im_8 !== Rtri_im_8_ref) begin
          Rtri_im_8_testFailure <= 1'b1;
          $display("ERROR in Rtri_im_8 at time %t : Expected '%h' Actual '%h'", $time, Rtri_im_8_ref, Rtri_im_8);
        end
      end
    end

  // Data source for Rtri_re_0_im_9_expected
  assign Rtri_re_0_im_9_expected_1 = 16'sb0000000000000000;

  // Bypass register to hold Rtri_im_9_ref
  always @(posedge clk or posedge reset)
    begin : DataHold_Rtri_im_9_ref
      if (reset) begin
        Rtri_im_9_ref_hold <= 0;
      end
      else begin
        if (ce_out) begin
          Rtri_im_9_ref_hold <= Rtri_re_0_im_9_expected_1;
        end
      end
    end

  // Data source for Rtri_re_0_im_9_expected
  assign Rtri_im_9_ref = (ce_out == 1'b0 ? Rtri_im_9_ref_hold :
              16'sb0000000000000000);

  always @(posedge clk or posedge reset)
    begin : Rtri_im_9_checker
      if (reset == 1'b1) begin
        Rtri_im_9_testFailure <= 1'b0;
      end
      else begin
        if (Rtri_re_0_chkdata == 1'b1 && Rtri_im_9 !== Rtri_im_9_ref) begin
          Rtri_im_9_testFailure <= 1'b1;
          $display("ERROR in Rtri_im_9 at time %t : Expected '%h' Actual '%h'", $time, Rtri_im_9_ref, Rtri_im_9);
        end
      end
    end

  assign valid_ignCntDone = valid_chkcnt != 2'b10;

  assign valid_needToCount = ce_out & valid_ignCntDone;

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 2
  always @(posedge clk or posedge reset)
    begin : valid_IgnoreDataChecking_process
      if (reset == 1'b1) begin
        valid_chkcnt <= 2'b00;
      end
      else begin
        if (valid_needToCount) begin
          if (valid_chkcnt >= 2'b10) begin
            valid_chkcnt <= 2'b00;
          end
          else begin
            valid_chkcnt <= valid_chkcnt + 2'b01;
          end
        end
      end
    end

  assign valid_chkenb = valid_chkcnt == 2'b10;

  assign valid_chkdata = ce_out & valid_chkenb;

  assign #1 valid_addr_delay_1 = Rtri_re_0_addr;

  // Data source for valid_expected
  initial
    begin : valid_expected_fileread
      fp_valid_expected = $fopen("valid_expected.dat", "r");
      status_valid_expected = $rewind(fp_valid_expected);
    end

  always @(valid_addr_delay_1,  tb_enb)
    begin
      if (tb_enb == 0) begin
        valid_expected <= 1'bx;
      end
      else  begin
        status_valid_expected = $fscanf(fp_valid_expected, "%h", valid_expected);
      end
    end

  // Bypass register to hold valid_ref
  always @(posedge clk or posedge reset)
    begin : DataHold_valid_ref
      if (reset) begin
        valid_ref_hold <= 0;
      end
      else begin
        if (ce_out) begin
          valid_ref_hold <= valid_expected;
        end
      end
    end

  assign valid_refTmp = valid_expected;

  assign valid_ref = (ce_out == 1'b0 ? valid_ref_hold :
              valid_refTmp);

  always @(posedge clk or posedge reset)
    begin : valid_checker
      if (reset == 1'b1) begin
        valid_testFailure <= 1'b0;
      end
      else begin
        if (valid_chkdata == 1'b1 && valid !== valid_ref) begin
          valid_testFailure <= 1'b1;
          $display("ERROR in valid at time %t : Expected '%h' Actual '%h'", $time, valid_ref, valid);
        end
      end
    end

  always @(Rtri_im_0_testFailure, Rtri_im_1_testFailure, Rtri_im_2_testFailure,
       Rtri_im_3_testFailure, Rtri_im_4_testFailure, Rtri_im_5_testFailure,
       Rtri_im_6_testFailure, Rtri_im_7_testFailure, Rtri_im_8_testFailure,
       Rtri_im_9_testFailure, Rtri_re_0_testFailure, Rtri_re_1_testFailure,
       Rtri_re_2_testFailure, Rtri_re_3_testFailure, Rtri_re_4_testFailure,
       Rtri_re_5_testFailure, Rtri_re_6_testFailure, Rtri_re_7_testFailure,
       Rtri_re_8_testFailure, Rtri_re_9_testFailure, valid_testFailure) begin
    testFailure = valid_testFailure | (Rtri_im_9_testFailure | (Rtri_im_8_testFailure | (Rtri_im_7_testFailure | (Rtri_im_6_testFailure | (Rtri_im_5_testFailure | (Rtri_im_4_testFailure | (Rtri_im_3_testFailure | (Rtri_im_2_testFailure | (Rtri_im_1_testFailure | (Rtri_im_0_testFailure | (Rtri_re_9_testFailure | (Rtri_re_8_testFailure | (Rtri_re_7_testFailure | (Rtri_re_6_testFailure | (Rtri_re_5_testFailure | (Rtri_re_4_testFailure | (Rtri_re_3_testFailure | (Rtri_re_2_testFailure | (Rtri_re_0_testFailure | Rtri_re_1_testFailure)))))))))))))))))));
  end

  always @(posedge clk)
    begin : completed_msg
      if (snkDone == 1'b1) begin
        if (testFailure == 1'b0) begin
          $display("**************TEST COMPLETED (PASSED)**************");
        end
        else begin
          $display("**************TEST COMPLETED (FAILED)**************");
        end
      end
    end

endmodule  // covariance_core_fixpt_tb

