%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%          Generated by MATLAB 25.1 and Fixed-Point Designer 25.1          %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [Rtri,valid] = covariance_core_wrapper_fixpt(samp_re,samp_im,samp_valid,frame_start)
    fm = get_fimath();
    samp_re_in = fi( samp_re, 1, 16, 13, fm );
    samp_im_in = fi( samp_im, 1, 16, 13, fm );
    samp_valid_in = samp_valid;
    frame_start_in = frame_start;
    [Rtri_out,valid_out] = covariance_core_fixpt( samp_re_in, samp_im_in, samp_valid_in, frame_start_in );
    Rtri = double( Rtri_out );
    valid = valid_out;
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Nearest',...
	     'OverflowAction', 'Saturate', 'ProductMode', 'SpecifyPrecision',...
	     'ProductWordLength', 40,...
	     'ProductFractionLength', 30,...
	     'SumMode', 'SpecifyPrecision',...
	     'SumWordLength', 40,...
	     'SumFractionLength', 30,...
	     'CastBeforeSum', true);
end
