%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%          Generated by MATLAB 25.1 and Fixed-Point Designer 25.1          %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%#codegen
function [Rtri, valid] = covariance_core_fixpt(samp_re, samp_im, samp_valid, frame_start)
%PL block v3: STREAMING covariance accumulator - one SCALAR complex
% sample per call, matching real ADC/UART ingest (ingest delivers one
% element at a time) and matching selftest_bram.v's existing native
% output order exactly (no changes needed there).
%
% WHY THE REWRITE (v2 -> v3): v2 took the whole 4x256 frame as one
% function argument. HDL Coder exposed that as a fully parallel port:
% 2048 real values x 16 bit = ~32768 wires, tripping "IO Pin Count 33092
% exceeds threshold 5000" and forcing "4096x faster clock" to squeeze
% 256 MACs into one base-rate tick. Root cause: batch design instead of
% streaming. Fix is MathWorks' documented pattern for exactly this -
% persistent variables as the accumulator (maps to hardware registers),
% called once per sample. Verified bit-identical to the batch X*X'
% computation (max diff 0.0) before shipping.
%
% Protocol: samples arrive in MATLAB X(:) column-major order, i.e. all
% M=4 antenna elements of time-sample 1, then all 4 of time-sample 2,
% etc. (1024 calls with samp_valid=true per 256-sample frame). Buffers
% 4 consecutive scalar arrivals into one antenna-vector, accumulates
% its 4x4 outer product, repeats 256 times, then asserts valid+Rtri.
    fm = get_fimath();

    persistent R buf pos scount;
    if isempty(R)
        R = fi(complex(zeros(4,4)), 1, 40, 30, fm); buf = fi(complex(zeros(4,1)), 1, 16, 13, fm);
        pos = fi(int32(0), 0, 2, 0, fm); scount = fi(int32(0), 0, 9, 0, fm);
    end
    if frame_start
        R(:) = complex(zeros(4,4)); pos(:) = int32(0); scount(:) = int32(0);
    end
    valid = false;
    Rtri = fi(complex(zeros(10,1)), 1, 16, 14, fm);
    if samp_valid
        buf(pos+fi(1, 0, 1, 0, fm)) = complexx(samp_re, samp_im);
        if pos == fi(3, 0, 2, 0, fm)                          % 4th element of this snapshot arrived
            R(:) = R + (buf * buf');         % one outer-product MAC (DSP48-style)
            scount(:) = scount + fi(1, 0, 1, 0, fm);
            pos(:) = int32(0);
            if scount == fi(256, 0, 9, 0, fm)
                Rs = fi(R * (fi(2^-8, 0, 16, 23, fm)), 1, 16, 14, fm);             % = /256, exact, HDL-safe (no divider)
                idx = fi(1, 0, 4, 0, fm);
                for i=1:4
                    for j=i:4
                        Rtri(idx) = Rs(i,j); idx(:) = idx+fi(1, 0, 1, 0, fm);
                    end
                end
                valid(:) = true;
                scount(:) = int32(0);
            end
        else
            pos(:) = pos + fi(1, 0, 1, 0, fm);
        end
    end
end



function c = complexx(varargin)
    coder.inline( 'always' );
    if nargin==2
        re = varargin{ 1 };
        im = varargin{ 2 };
        if isfi( re ) && isfi( im )
            % Choose wider type
            NT = fixed.aggregateType( re, im );
            c = complex( fi( re, NT ), fi( im, NT ) );
        else
            c = complex( re, im );
        end
    elseif nargin==1
        c = complex( varargin{ 1 } );
    end
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Nearest',...
	     'OverflowAction', 'Saturate', 'ProductMode', 'SpecifyPrecision',...
	     'ProductWordLength', 40,...
	     'ProductFractionLength', 30,...
	     'SumMode', 'SpecifyPrecision',...
	     'SumWordLength', 40,...
	     'SumFractionLength', 30,...
	     'CastBeforeSum', true);
end
