// -------------------------------------------------------------
// 
// File Name: C:\Users\Shashank Madhusudan\OneDrive\Desktop\Radar-Aided-Beam-Tracking\codegen\covariance_core\hdlsrc\covariance_core_fixpt.v
// Created: 2026-07-19 15:08:39
// 
// Generated by MATLAB 25.1, MATLAB Coder 25.1 and HDL Coder 25.1
// 
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Design base rate: 0.0125
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// Rtri_re_0                     ce_out        1
// Rtri_re_1                     ce_out        1
// Rtri_re_2                     ce_out        1
// Rtri_re_3                     ce_out        1
// Rtri_re_4                     ce_out        1
// Rtri_re_5                     ce_out        1
// Rtri_re_6                     ce_out        1
// Rtri_re_7                     ce_out        1
// Rtri_re_8                     ce_out        1
// Rtri_re_9                     ce_out        1
// Rtri_im_0                     ce_out        1
// Rtri_im_1                     ce_out        1
// Rtri_im_2                     ce_out        1
// Rtri_im_3                     ce_out        1
// Rtri_im_4                     ce_out        1
// Rtri_im_5                     ce_out        1
// Rtri_im_6                     ce_out        1
// Rtri_im_7                     ce_out        1
// Rtri_im_8                     ce_out        1
// Rtri_im_9                     ce_out        1
// valid                         ce_out        1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: covariance_core_fixpt
// Source Path: covariance_core_fixpt
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module covariance_core_fixpt
          (clk,
           reset,
           clk_enable,
           samp_re,
           samp_im,
           samp_valid,
           frame_start,
           ce_out,
           Rtri_re_0,
           Rtri_re_1,
           Rtri_re_2,
           Rtri_re_3,
           Rtri_re_4,
           Rtri_re_5,
           Rtri_re_6,
           Rtri_re_7,
           Rtri_re_8,
           Rtri_re_9,
           Rtri_im_0,
           Rtri_im_1,
           Rtri_im_2,
           Rtri_im_3,
           Rtri_im_4,
           Rtri_im_5,
           Rtri_im_6,
           Rtri_im_7,
           Rtri_im_8,
           Rtri_im_9,
           valid);


  input   clk;
  input   reset;
  input   clk_enable;
  input   signed [15:0] samp_re;  // sfix16_En13
  input   signed [15:0] samp_im;  // sfix16_En13
  input   samp_valid;
  input   frame_start;
  output  ce_out;
  output  signed [15:0] Rtri_re_0;  // sfix16_En14
  output  signed [15:0] Rtri_re_1;  // sfix16_En14
  output  signed [15:0] Rtri_re_2;  // sfix16_En14
  output  signed [15:0] Rtri_re_3;  // sfix16_En14
  output  signed [15:0] Rtri_re_4;  // sfix16_En14
  output  signed [15:0] Rtri_re_5;  // sfix16_En14
  output  signed [15:0] Rtri_re_6;  // sfix16_En14
  output  signed [15:0] Rtri_re_7;  // sfix16_En14
  output  signed [15:0] Rtri_re_8;  // sfix16_En14
  output  signed [15:0] Rtri_re_9;  // sfix16_En14
  output  signed [15:0] Rtri_im_0;  // sfix16_En14
  output  signed [15:0] Rtri_im_1;  // sfix16_En14
  output  signed [15:0] Rtri_im_2;  // sfix16_En14
  output  signed [15:0] Rtri_im_3;  // sfix16_En14
  output  signed [15:0] Rtri_im_4;  // sfix16_En14
  output  signed [15:0] Rtri_im_5;  // sfix16_En14
  output  signed [15:0] Rtri_im_6;  // sfix16_En14
  output  signed [15:0] Rtri_im_7;  // sfix16_En14
  output  signed [15:0] Rtri_im_8;  // sfix16_En14
  output  signed [15:0] Rtri_im_9;  // sfix16_En14
  output  valid;


  wire enb_1_80_1;
  wire enb_1_8_0;
  wire enb_1_80_0;
  wire enb_1_5_0;
  wire clk_enable_1;
  reg [3:0] counterSig;  // ufix4
  wire compareSig;
  wire samp_valid_rateChange;
  reg  [9:0] delayMatch_reg;  // ufix1 [10]
  wire samp_valid_rateChange_1;
  wire signed [15:0] Rtri_re [0:9];  // sfix16_En14 [10]
  wire signed [15:0] Rtri_im [0:9];  // sfix16_En14 [10]
  wire signed [15:0] ratechange_splitcomp_out0_re;  // sfix16_En14
  wire signed [15:0] ratechange_splitcomp_out0_im;  // sfix16_En14
  wire signed [15:0] ratechange_splitcomp_out1_re;  // sfix16_En14
  wire signed [15:0] ratechange_splitcomp_out1_im;  // sfix16_En14
  wire signed [15:0] ratechange_splitcomp_out2_re;  // sfix16_En14
  wire signed [15:0] ratechange_splitcomp_out2_im;  // sfix16_En14
  wire signed [15:0] ratechange_splitcomp_out3_re;  // sfix16_En14
  wire signed [15:0] ratechange_splitcomp_out3_im;  // sfix16_En14
  wire signed [15:0] ratechange_splitcomp_out4_re;  // sfix16_En14
  wire signed [15:0] ratechange_splitcomp_out4_im;  // sfix16_En14
  wire signed [15:0] ratechange_splitcomp_out5_re;  // sfix16_En14
  wire signed [15:0] ratechange_splitcomp_out5_im;  // sfix16_En14
  wire signed [15:0] ratechange_splitcomp_out6_re;  // sfix16_En14
  wire signed [15:0] ratechange_splitcomp_out6_im;  // sfix16_En14
  wire signed [15:0] ratechange_splitcomp_out7_re;  // sfix16_En14
  wire signed [15:0] ratechange_splitcomp_out7_im;  // sfix16_En14
  wire signed [15:0] ratechange_splitcomp_out8_re;  // sfix16_En14
  wire signed [15:0] ratechange_splitcomp_out8_im;  // sfix16_En14
  wire signed [15:0] ratechange_splitcomp_out9_re;  // sfix16_En14
  wire signed [15:0] ratechange_splitcomp_out9_im;  // sfix16_En14
  wire signed [15:0] Rtri_serializer_re;  // sfix16_En14
  wire signed [15:0] Rtri_serializer_im;  // sfix16_En14
  reg signed [15:0] reduced_reg_re [0:9];  // sfix16_En14 [10]
  reg signed [15:0] reduced_reg_im [0:9];  // sfix16_En14 [10]
  reg signed [15:0] reduced_reg_next_re [0:9];  // sfix16_En14 [10]
  reg signed [15:0] reduced_reg_next_im [0:9];  // sfix16_En14 [10]
  reg signed [15:0] Rtri_serializer_re_1;  // sfix16_En14
  reg signed [15:0] Rtri_serializer_im_1;  // sfix16_En14
  wire [39:0] s;  // ufix40_En30
  wire [1:0] pos;  // ufix2
  wire [1:0] pos_1;  // ufix2
  wire [1:0] tmp;  // ufix2
  wire [39:0] tmp_1;  // ufix40_En30
  wire [40:0] adder_add_cast;  // ufix41_En30
  wire [40:0] adder_add_cast_1;  // ufix41_En30
  wire [40:0] adder_add_temp;  // ufix41_En30
  wire [39:0] tmp_2;  // ufix40_En30
  wire [1:0] tmp_3;  // ufix2
  wire tmp_4;
  wire [1:0] tmp_5;  // ufix2
  wire [1:0] tmp_6;  // ufix2
  reg [1:0] pos_2;  // ufix2
  wire tmp_rateChange;
  reg  [9:0] delayMatch_reg_1;  // ufix1 [10]
  wire tmp_rateChange_1;
  wire [8:0] scount;  // ufix9
  wire [8:0] scount_1;  // ufix9
  wire [39:0] s_1;  // ufix40_En30
  wire scount_2;
  wire [8:0] scount_3;  // ufix9
  wire [8:0] tmp_7;  // ufix9
  wire [8:0] tmp_8;  // ufix9
  wire [8:0] tmp_9;  // ufix9
  wire [8:0] tmp_10;  // ufix9
  reg [8:0] scount_4;  // ufix9
  wire [39:0] tmp_11;  // ufix40_En30
  wire [40:0] adder_add_cast_2;  // ufix41_En30
  wire [40:0] adder_add_cast_3;  // ufix41_En30
  wire [40:0] adder_add_temp_1;  // ufix41_En30
  wire [39:0] tmp_12;  // ufix40_En30
  wire scount_rateChange;
  reg  [9:0] delayMatch_reg_2;  // ufix1 [10]
  wire scount_rateChange_1;
  wire signed [31:0] j;  // int32
  wire signed [31:0] i;  // int32
  wire [3:0] idx;  // ufix4
  wire signed [15:0] tmp_13;  // sfix16_En6
  wire signed [15:0] tmp_14;  // sfix16_En6
  wire sel;
  wire s_2;
  wire sel_2;
  wire [39:0] tmp_15;  // ufix40_En30
  wire [39:0] s_3;  // ufix40_En30
  wire [40:0] adder_add_cast_4;  // ufix41_En30
  wire [40:0] adder_add_cast_5;  // ufix41_En30
  wire [40:0] adder_add_temp_2;  // ufix41_En30
  wire [39:0] tmp_16;  // ufix40_En30
  wire signed [31:0] tmp_17;  // int32
  wire signed [31:0] tmp_18;  // int32
  reg signed [15:0] buf_r [0:3];  // sfix16_En13 [4]
  reg signed [15:0] buf_r_reg_reg [0:3];  // sfix16 [4]
  wire signed [15:0] buf_r_reg_reg_next [0:3];  // sfix16_En13 [4]
  wire signed [15:0] buf_r_1 [0:3];  // sfix16_En13 [4]
  wire sel_1;
  wire s_4;
  wire sel_2_1;
  wire [39:0] tmp_19;  // ufix40_En30
  wire [39:0] s_5;  // ufix40_En30
  wire [40:0] adder_add_cast_6;  // ufix41_En30
  wire [40:0] adder_add_cast_7;  // ufix41_En30
  wire [40:0] adder_add_temp_3;  // ufix41_En30
  wire [39:0] tmp_20;  // ufix40_En30
  wire signed [31:0] tmp_21;  // int32
  wire signed [31:0] tmp_22;  // int32
  reg signed [15:0] buf_i [0:3];  // sfix16_En13 [4]
  reg signed [15:0] buf_i_reg_reg [0:3];  // sfix16 [4]
  wire signed [15:0] buf_i_reg_reg_next [0:3];  // sfix16_En13 [4]
  wire signed [15:0] buf_i_1 [0:3];  // sfix16_En13 [4]
  wire signed [15:0] tmp_23 [0:3] [0:3];  // sfix16_En6 [4x4]
  wire signed [15:0] c135_tmp [0:15];  // sfix16_En6 [16]
  wire signed [15:0] Rr [0:3] [0:3];  // sfix16_En6 [4x4]
  wire signed [15:0] c125_Rr [0:15];  // sfix16_En6 [16]
  wire signed [15:0] c125_tmp [0:15];  // sfix16_En6 [16]
  reg signed [15:0] c125_tmp_1 [0:15];  // sfix16_En6 [16]
  wire signed [15:0] tmp_24 [0:3] [0:3];  // sfix16_En6 [4x4]
  wire signed [15:0] c126_tmp [0:15];  // sfix16_En6 [16]
  reg signed [15:0] c133_Rr [0:15];  // sfix16_En6 [16]
  wire signed [15:0] Rr_1 [0:3] [0:3];  // sfix16_En6 [4x4]
  wire signed [15:0] c124_Rr [0:15];  // sfix16_En6 [16]
  wire signed [15:0] Rr_2 [0:3] [0:3];  // sfix16_En6 [4x4]
  wire signed [15:0] c124_Rr_1 [0:15];  // sfix16_En6 [16]
  reg signed [15:0] c124_tmp [0:15];  // sfix16_En6 [16]
  wire signed [15:0] c126_tmp_1 [0:15];  // sfix16_En6 [16]
  reg signed [15:0] c126_tmp_2 [0:15];  // sfix16_En6 [16]
  wire signed [15:0] tmp_25 [0:3] [0:3];  // sfix16_En6 [4x4]
  wire signed [15:0] c128_tmp [0:15];  // sfix16_En6 [16]
  reg signed [15:0] Rr_reg_reg [0:15];  // sfix16 [16]
  wire signed [15:0] Rr_reg_reg_next [0:15];  // sfix16_En6 [16]
  wire signed [15:0] c128_Rr [0:15];  // sfix16_En6 [16]
  wire signed [15:0] c133_Rr_1 [0:15];  // sfix16_En6 [16]
  wire signed [15:0] Ri [0:3] [0:3];  // sfix16_En6 [4x4]
  wire signed [15:0] c133_Ri [0:15];  // sfix16_En6 [16]
  reg signed [15:0] c133_Ri_1 [0:15];  // sfix16_En6 [16]
  wire signed [15:0] Ri_1 [0:3] [0:3];  // sfix16_En6 [4x4]
  wire signed [15:0] c134_Ri [0:15];  // sfix16_En6 [16]
  reg signed [15:0] c135_Ri [0:15];  // sfix16_En6 [16]
  wire signed [15:0] Ri_2 [0:3] [0:3];  // sfix16_En6 [4x4]
  wire signed [15:0] c129_Ri [0:15];  // sfix16_En6 [16]
  wire signed [15:0] tmp_26 [0:3] [0:3];  // sfix16_En6 [4x4]
  wire signed [15:0] c129_tmp [0:15];  // sfix16_En6 [16]
  reg signed [15:0] c129_tmp_1 [0:15];  // sfix16_En6 [16]
  wire signed [15:0] tmp_27 [0:3] [0:3];  // sfix16_En6 [4x4]
  wire signed [15:0] c130_tmp [0:15];  // sfix16_En6 [16]
  wire signed [15:0] c130_tmp_1 [0:15];  // sfix16_En6 [16]
  reg signed [15:0] c130_tmp_2 [0:15];  // sfix16_En6 [16]
  wire signed [15:0] tmp_28 [0:3] [0:3];  // sfix16_En6 [4x4]
  wire signed [15:0] c132_tmp [0:15];  // sfix16_En6 [16]
  reg signed [15:0] Ri_reg_reg [0:15];  // sfix16 [16]
  wire signed [15:0] Ri_reg_reg_next [0:15];  // sfix16_En6 [16]
  wire signed [15:0] c132_Ri [0:15];  // sfix16_En6 [16]
  wire signed [15:0] c134_Ri_1 [0:15];  // sfix16_En6 [16]
  reg signed [15:0] c134_tmp [0:15];  // sfix16_En6 [16]
  wire signed [15:0] c135_tmp_1 [0:15];  // sfix16_En6 [16]
  reg signed [15:0] c135_Rr [0:15];  // sfix16_En6 [16]
  wire signed [15:0] c181_Rr [0:15];  // sfix16_En6 [16]
  wire signed [15:0] c181_Rr_1 [0:15];  // sfix16_En6 [16]
  wire signed [15:0] Rr_3 [0:3] [0:3];  // sfix16_En6 [4x4]
  wire signed [15:0] c182_Ri [0:15];  // sfix16_En6 [16]
  wire signed [15:0] c182_Ri_1 [0:15];  // sfix16_En6 [16]
  wire signed [15:0] Ri_3 [0:3] [0:3];  // sfix16_En6 [4x4]
  wire enbSig_1;
  wire signed [15:0] Rtri_re_0_1;  // sfix16_En14
  wire signed [15:0] Rtri_re_1_1;  // sfix16_En14
  wire signed [15:0] Rtri_re_2_1;  // sfix16_En14
  wire signed [15:0] Rtri_re_3_1;  // sfix16_En14
  wire signed [15:0] Rtri_re_4_1;  // sfix16_En14
  wire signed [15:0] Rtri_re_5_1;  // sfix16_En14
  wire signed [15:0] Rtri_re_6_1;  // sfix16_En14
  wire signed [15:0] Rtri_re_7_1;  // sfix16_En14
  wire signed [15:0] Rtri_re_8_1;  // sfix16_En14
  wire signed [15:0] Rtri_re_9_1;  // sfix16_En14
  wire signed [15:0] Rtri_im_0_1;  // sfix16_En14
  wire signed [15:0] Rtri_im_1_1;  // sfix16_En14
  wire signed [15:0] Rtri_im_2_1;  // sfix16_En14
  wire signed [15:0] Rtri_im_3_1;  // sfix16_En14
  wire signed [15:0] Rtri_im_4_1;  // sfix16_En14
  wire signed [15:0] Rtri_im_5_1;  // sfix16_En14
  wire signed [15:0] Rtri_im_6_1;  // sfix16_En14
  wire signed [15:0] Rtri_im_7_1;  // sfix16_En14
  wire signed [15:0] Rtri_im_8_1;  // sfix16_En14
  wire signed [15:0] Rtri_im_9_1;  // sfix16_En14
  wire signed [15:0] Rtri_re_10 [0:9];  // sfix16_En14 [10]
  wire signed [15:0] Rtri_im_10 [0:9];  // sfix16_En14 [10]
  reg signed [15:0] Rtri_downsample_bypass_reg_re [0:9];  // sfix16_En14 [10]
  reg signed [15:0] Rtri_downsample_bypass_reg_im [0:9];  // sfix16_En14 [10]
  reg signed [15:0] Rtri_downsample_bypass_reg_next_re [0:9];  // sfix16_En14 [10]
  reg signed [15:0] Rtri_downsample_bypass_reg_next_im [0:9];  // sfix16_En14 [10]
  reg signed [15:0] Rtri_re_11 [0:9];  // sfix16_En14 [10]
  reg signed [15:0] Rtri_im_11 [0:9];  // sfix16_En14 [10]
  wire signed [15:0] ratechange_splitcomp_out0_re_1;  // sfix16_En14
  wire signed [15:0] ratechange_splitcomp_out0_im_1;  // sfix16_En14
  wire signed [15:0] ratechange_splitcomp_out1_re_1;  // sfix16_En14
  wire signed [15:0] ratechange_splitcomp_out1_im_1;  // sfix16_En14
  wire signed [15:0] ratechange_splitcomp_out2_re_1;  // sfix16_En14
  wire signed [15:0] ratechange_splitcomp_out2_im_1;  // sfix16_En14
  wire signed [15:0] ratechange_splitcomp_out3_re_1;  // sfix16_En14
  wire signed [15:0] ratechange_splitcomp_out3_im_1;  // sfix16_En14
  wire signed [15:0] ratechange_splitcomp_out4_re_1;  // sfix16_En14
  wire signed [15:0] ratechange_splitcomp_out4_im_1;  // sfix16_En14
  wire signed [15:0] ratechange_splitcomp_out5_re_1;  // sfix16_En14
  wire signed [15:0] ratechange_splitcomp_out5_im_1;  // sfix16_En14
  wire signed [15:0] ratechange_splitcomp_out6_re_1;  // sfix16_En14
  wire signed [15:0] ratechange_splitcomp_out6_im_1;  // sfix16_En14
  wire signed [15:0] ratechange_splitcomp_out7_re_1;  // sfix16_En14
  wire signed [15:0] ratechange_splitcomp_out7_im_1;  // sfix16_En14
  wire signed [15:0] ratechange_splitcomp_out8_re_1;  // sfix16_En14
  wire signed [15:0] ratechange_splitcomp_out8_im_1;  // sfix16_En14
  wire signed [15:0] ratechange_splitcomp_out9_re_1;  // sfix16_En14
  wire signed [15:0] ratechange_splitcomp_out9_im_1;  // sfix16_En14
  wire signed [15:0] Rtri_serializer_re_2;  // sfix16_En14
  wire signed [15:0] Rtri_serializer_im_2;  // sfix16_En14
  wire signed [15:0] tmp_re;  // sfix16_En14
  wire signed [15:0] tmp_im;  // sfix16_En14
  wire signed [15:0] tmp_re_1;  // sfix16_En14
  wire signed [15:0] tmp_im_1;  // sfix16_En14
  wire signed [15:0] tmp_re_2;  // sfix16_En14
  wire signed [15:0] tmp_im_2;  // sfix16_En14
  reg signed [15:0] tapped_delay_reg_re [0:8];  // sfix16_En14 [9]
  reg signed [15:0] tapped_delay_reg_im [0:8];  // sfix16_En14 [9]
  reg signed [15:0] tapped_delay_reg_next_re [0:8];  // sfix16_En14 [9]
  reg signed [15:0] tapped_delay_reg_next_im [0:8];  // sfix16_En14 [9]
  reg signed [15:0] tappedDelaySig_re [0:9];  // sfix16_En14 [10]
  reg signed [15:0] tappedDelaySig_im [0:9];  // sfix16_En14 [10]
  reg signed [15:0] unit_delay_reg_re [0:9];  // sfix16_En14 [10]
  reg signed [15:0] unit_delay_reg_im [0:9];  // sfix16_En14 [10]
  wire signed [15:0] unit_delay_reg_next_re [0:9];  // sfix16_En14 [10]
  wire signed [15:0] unit_delay_reg_next_im [0:9];  // sfix16_En14 [10]
  wire signed [15:0] unitDelaySig_re [0:9];  // sfix16_En14 [10]
  wire signed [15:0] unitDelaySig_im [0:9];  // sfix16_En14 [10]
  wire valid_1;
  wire valid_2;
  wire tmp_29;
  wire tmp_30;
  wire tmp_31;
  reg  [1:0] delayMatch_reg_3;  // ufix1 [2]
  wire tmp_32;
  reg signed [31:0] reduced_t_0_0;  // int32
  reg signed [31:0] reduced_t_0_1;  // int32
  reg signed [31:0] reduced_t_1;  // int32
  reg signed [31:0] buf_r_reg_t_0_1;  // int32
  reg signed [31:0] buf_r_reg_t_1;  // int32
  reg signed [31:0] p47buf_r_t_0;  // int32
  reg signed [31:0] buf_i_reg_t_0_1;  // int32
  reg signed [31:0] buf_i_reg_t_1;  // int32
  reg signed [31:0] p51buf_i_t_0;  // int32
  reg signed [31:0] p37_t_0_0;  // int32
  reg signed [31:0] p37_t_1;  // int32
  reg signed [31:0] p72_t_0_0;  // int32
  reg signed [31:0] p72_t_1;  // int32
  reg signed [31:0] p31_t_0_0;  // int32
  reg signed [31:0] p31_t_1;  // int32
  reg signed [31:0] Rr_reg_t_0_1;  // int32
  reg signed [31:0] Rr_reg_t_1;  // int32
  reg signed [31:0] p74_i;  // int32
  reg signed [15:0] p74_Ri [0:15];  // sfix16_En6 [16]
  reg signed [15:0] p74_Rr [0:15];  // sfix16_En6 [16]
  reg signed [31:0] p74_j;  // int32
  reg signed [31:0] p74_t_0;  // int32
  reg signed [63:0] p74_add_cast;  // sfix64
  reg signed [63:0] p74_add_cast_0;  // sfix64
  reg signed [31:0] p38_t_0_0;  // int32
  reg signed [31:0] p38_t_1;  // int32
  reg signed [31:0] p33_t_0_0;  // int32
  reg signed [31:0] p33_t_1;  // int32
  reg signed [31:0] Ri_reg_t_0_1;  // int32
  reg signed [31:0] Ri_reg_t_1;  // int32
  reg signed [31:0] p73_t_0_0;  // int32
  reg signed [31:0] p73_t_1;  // int32
  reg signed [31:0] p46_i;  // int32
  reg signed [15:0] p46_Ri [0:15];  // sfix16_En6 [16]
  reg signed [15:0] p46_Rr [0:15];  // sfix16_En6 [16]
  reg signed [31:0] p46_j;  // int32
  reg signed [31:0] p46_t_0;  // int32
  reg signed [31:0] p46_t_1;  // int32
  reg signed [63:0] p46_add_cast;  // sfix64
  reg signed [63:0] p46_add_cast_0;  // sfix64
  reg signed [39:0] p46_add_cast_1;  // sfix40_En30
  reg signed [40:0] p46_add_cast_2;  // sfix41_En30
  reg signed [31:0] p46_mul_temp;  // sfix32_En26
  reg signed [39:0] p46_add_cast_3;  // sfix40_En30
  reg signed [31:0] p46_mul_temp_0;  // sfix32_En26
  reg signed [39:0] p46_add_cast_4;  // sfix40_En30
  reg signed [39:0] p46_add_temp;  // sfix40_En30
  reg signed [40:0] p46_add_cast_5;  // sfix41_En30
  reg signed [40:0] p46_add_temp_0;  // sfix41_En30
  reg signed [39:0] p46_cast;  // sfix40_En30
  reg signed [63:0] p46_add_cast_6;  // sfix64
  reg signed [63:0] p46_add_cast_7;  // sfix64
  reg signed [39:0] p46_add_cast_8;  // sfix40_En30
  reg signed [40:0] p46_add_cast_9;  // sfix41_En30
  reg signed [31:0] p46_mul_temp_1;  // sfix32_En26
  reg signed [39:0] p46_sub_cast;  // sfix40_En30
  reg signed [31:0] p46_mul_temp_2;  // sfix32_En26
  reg signed [39:0] p46_sub_cast_0;  // sfix40_En30
  reg signed [39:0] p46_sub_temp;  // sfix40_En30
  reg signed [40:0] p46_add_cast_10;  // sfix41_En30
  reg signed [40:0] p46_add_temp_1;  // sfix41_En30
  reg signed [39:0] p46_cast_0;  // sfix40_En30
  reg signed [31:0] Rtri_downsample_bypass_t_0;  // int32
  reg signed [31:0] Rtri_downsample_bypass_t_1;  // int32
  reg signed [31:0] Rtri_downsample_bypass_t_2;  // int32
  reg signed [31:0] Rtri_downsample_bypass_t_0_0;  // int32
  reg signed [31:0] Rtri_downsample_bypass_t_1_0;  // int32
  reg signed [31:0] tapped_delay_t_0_0;  // int32
  reg signed [31:0] tapped_delay_t_1;  // int32
  reg signed [31:0] tapped_delay_t_0_1;  // int32
  reg signed [31:0] tapped_delay_t_1_0;  // int32
  reg signed [31:0] unit_delay_t_0_0;  // int32
  reg signed [31:0] unit_delay_t_1;  // int32


  covariance_core_fixpt_enb_bypass u_covariance_core_fixpt_enb_bypass (.clk_1(clk),
                                                                       .reset_1(reset),
                                                                       .clk_enable_1(clk_enable),
                                                                       .clk_enable_2(clk_enable_1)
                                                                       );

  covariance_core_fixpt_tc u_covariance_core_fixpt_tc (.clk(clk),
                                                       .reset(reset),
                                                       .clk_enable(clk_enable_1),
                                                       .enb_1_5_0(enb_1_5_0),
                                                       .enb_1_8_0(enb_1_8_0),
                                                       .enb_1_80_0(enb_1_80_0),
                                                       .enb_1_80_1(enb_1_80_1)
                                                       );

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 9
  always @(posedge clk or posedge reset)
    begin : ctr_0_9_process
      if (reset == 1'b1) begin
        counterSig <= 4'b0000;
      end
      else begin
        if (enb_1_8_0) begin
          if (counterSig >= 4'b1001) begin
            counterSig <= 4'b0000;
          end
          else begin
            counterSig <= counterSig + 4'b0001;
          end
        end
      end
    end

  assign compareSig = counterSig == 4'b1001;

  assign samp_valid_rateChange = samp_valid;

  always @(posedge clk or posedge reset)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        delayMatch_reg <= {10{1'b0}};
      end
      else begin
        if (enb_1_8_0) begin
          delayMatch_reg[0] <= samp_valid_rateChange;
          delayMatch_reg[32'sd9:32'sd1] <= delayMatch_reg[32'sd8:32'sd0];
        end
      end
    end

  assign samp_valid_rateChange_1 = delayMatch_reg[9];


  genvar t_0;
  generate
    for(t_0 = 32'sd0; t_0 <= 32'sd9; t_0 = t_0 + 32'sd1) begin:Rtri_im_gen
      assign Rtri_re[t_0] = 16'sb0000000000000000;
      assign Rtri_im[t_0] = 16'sb0000000000000000;
    end
  endgenerate

  assign ratechange_splitcomp_out0_re = Rtri_re[0];

  assign ratechange_splitcomp_out0_im = Rtri_im[0];

  assign ratechange_splitcomp_out1_re = Rtri_re[1];

  assign ratechange_splitcomp_out1_im = Rtri_im[1];

  assign ratechange_splitcomp_out2_re = Rtri_re[2];

  assign ratechange_splitcomp_out2_im = Rtri_im[2];

  assign ratechange_splitcomp_out3_re = Rtri_re[3];

  assign ratechange_splitcomp_out3_im = Rtri_im[3];

  assign ratechange_splitcomp_out4_re = Rtri_re[4];

  assign ratechange_splitcomp_out4_im = Rtri_im[4];

  assign ratechange_splitcomp_out5_re = Rtri_re[5];

  assign ratechange_splitcomp_out5_im = Rtri_im[5];

  assign ratechange_splitcomp_out6_re = Rtri_re[6];

  assign ratechange_splitcomp_out6_im = Rtri_im[6];

  assign ratechange_splitcomp_out7_re = Rtri_re[7];

  assign ratechange_splitcomp_out7_im = Rtri_im[7];

  assign ratechange_splitcomp_out8_re = Rtri_re[8];

  assign ratechange_splitcomp_out8_im = Rtri_im[8];

  assign ratechange_splitcomp_out9_re = Rtri_re[9];

  assign ratechange_splitcomp_out9_im = Rtri_im[9];

  assign Rtri_serializer_re = (counterSig == 4'b0000 ? ratechange_splitcomp_out0_re :
              (counterSig == 4'b0001 ? ratechange_splitcomp_out1_re :
              (counterSig == 4'b0010 ? ratechange_splitcomp_out2_re :
              (counterSig == 4'b0011 ? ratechange_splitcomp_out3_re :
              (counterSig == 4'b0100 ? ratechange_splitcomp_out4_re :
              (counterSig == 4'b0101 ? ratechange_splitcomp_out5_re :
              (counterSig == 4'b0110 ? ratechange_splitcomp_out6_re :
              (counterSig == 4'b0111 ? ratechange_splitcomp_out7_re :
              (counterSig == 4'b1000 ? ratechange_splitcomp_out8_re :
              ratechange_splitcomp_out9_re)))))))));
  assign Rtri_serializer_im = (counterSig == 4'b0000 ? ratechange_splitcomp_out0_im :
              (counterSig == 4'b0001 ? ratechange_splitcomp_out1_im :
              (counterSig == 4'b0010 ? ratechange_splitcomp_out2_im :
              (counterSig == 4'b0011 ? ratechange_splitcomp_out3_im :
              (counterSig == 4'b0100 ? ratechange_splitcomp_out4_im :
              (counterSig == 4'b0101 ? ratechange_splitcomp_out5_im :
              (counterSig == 4'b0110 ? ratechange_splitcomp_out6_im :
              (counterSig == 4'b0111 ? ratechange_splitcomp_out7_im :
              (counterSig == 4'b1000 ? ratechange_splitcomp_out8_im :
              ratechange_splitcomp_out9_im)))))))));

  always @(posedge clk or posedge reset)
    begin : reduced_process
      if (reset == 1'b1) begin
        for(reduced_t_1 = 32'sd0; reduced_t_1 <= 32'sd9; reduced_t_1 = reduced_t_1 + 32'sd1) begin
          reduced_reg_re[reduced_t_1] <= 16'sb0000000000000000;
          reduced_reg_im[reduced_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb_1_8_0) begin
          for(reduced_t_0_1 = 32'sd0; reduced_t_0_1 <= 32'sd9; reduced_t_0_1 = reduced_t_0_1 + 32'sd1) begin
            reduced_reg_re[reduced_t_0_1] <= reduced_reg_next_re[reduced_t_0_1];
            reduced_reg_im[reduced_t_0_1] <= reduced_reg_next_im[reduced_t_0_1];
          end
        end
      end
    end

  always @* begin
    Rtri_serializer_re_1 = reduced_reg_re[9];
    Rtri_serializer_im_1 = reduced_reg_im[9];
    reduced_reg_next_re[0] = Rtri_serializer_re;
    reduced_reg_next_im[0] = Rtri_serializer_im;

    for(reduced_t_0_0 = 32'sd0; reduced_t_0_0 <= 32'sd8; reduced_t_0_0 = reduced_t_0_0 + 32'sd1) begin
      reduced_reg_next_re[reduced_t_0_0 + 32'sd1] = reduced_reg_re[reduced_t_0_0];
      reduced_reg_next_im[reduced_t_0_0 + 32'sd1] = reduced_reg_im[reduced_t_0_0];
    end

  end

  assign s = 40'h0040000000;

  assign pos = 2'b00;

  assign pos_1 = 2'b00;

  assign tmp_1 = {8'b0, {tmp, 30'b000000000000000000000000000000}};

  assign adder_add_cast = {1'b0, tmp_1};
  assign adder_add_cast_1 = {1'b0, s};
  assign adder_add_temp = adder_add_cast + adder_add_cast_1;
  assign tmp_2 = (adder_add_temp[40] != 1'b0 ? 40'hFFFFFFFFFF :
              adder_add_temp[39:0]);

  assign tmp_3 = ((tmp_2[39:32] != 8'b00000000) || (tmp_2[31:30] == 2'b11) ? 2'b11 :
              tmp_2[31:30] + tmp_2[29]);

  assign tmp_5 = (tmp_4 == 1'b0 ? tmp_3 :
              pos);

  assign tmp_6 = (samp_valid == 1'b0 ? tmp :
              tmp_5);

  always @(posedge clk or posedge reset)
    begin : pos_reg_process
      if (reset == 1'b1) begin
        pos_2 <= 2'b00;
      end
      else begin
        if (enb_1_80_0) begin
          pos_2 <= tmp_6;
        end
      end
    end

  assign tmp = (frame_start == 1'b0 ? pos_2 :
              pos_1);

  assign tmp_4 = tmp == 2'b11;

  assign tmp_rateChange = tmp_4;

  always @(posedge clk or posedge reset)
    begin : delayMatch_1_process
      if (reset == 1'b1) begin
        delayMatch_reg_1 <= {10{1'b0}};
      end
      else begin
        if (enb_1_8_0) begin
          delayMatch_reg_1[0] <= tmp_rateChange;
          delayMatch_reg_1[32'sd9:32'sd1] <= delayMatch_reg_1[32'sd8:32'sd0];
        end
      end
    end

  assign tmp_rateChange_1 = delayMatch_reg_1[9];

  assign scount = 9'b000000000;

  // %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  //                                                                          %
  //          Generated by MATLAB 25.1 and Fixed-Point Designer 25.1          %
  //                                                                          %
  // %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  // PL block v4: streaming covariance - SCALAR-ACCESS accumulation.
  // v3 used R(:) = R + (buf*buf'): a whole-matrix read-modify-write. HDL
  // conformance warned "'R': RAM mapping failed ... non-scalar sub-matrix
  // access" / "unable to apply vector streaming". Under StreamLoops that
  // matrix RMW is scheduled across sub-rate phases and the R read races
  // its own writeback: generated RTL retains ~1 snapshot of 256 (verified:
  // MathWorks' own generated TB fails identically in Vivado AND Verilator
  // while the sequential fixed-point MATLAB sim passes). v4 does what the
  // warning asks: explicit scalar element updates only.
  assign scount_1 = 9'b000000000;

  assign s_1 = 40'h0040000000;

  assign tmp_7 = (scount_2 == 1'b0 ? scount_3 :
              scount);

  assign tmp_9 = (tmp_4 == 1'b0 ? tmp_8 :
              tmp_7);

  assign tmp_10 = (samp_valid == 1'b0 ? tmp_8 :
              tmp_9);

  always @(posedge clk or posedge reset)
    begin : scount_reg_process
      if (reset == 1'b1) begin
        scount_4 <= 9'b000000000;
      end
      else begin
        if (enb_1_80_0) begin
          scount_4 <= tmp_10;
        end
      end
    end

  assign tmp_8 = (frame_start == 1'b0 ? scount_4 :
              scount_1);

  assign tmp_11 = {1'b0, {tmp_8, 30'b000000000000000000000000000000}};

  assign adder_add_cast_2 = {1'b0, tmp_11};
  assign adder_add_cast_3 = {1'b0, s_1};
  assign adder_add_temp_1 = adder_add_cast_2 + adder_add_cast_3;
  assign tmp_12 = (adder_add_temp_1[40] != 1'b0 ? 40'hFFFFFFFFFF :
              adder_add_temp_1[39:0]);

  assign scount_3 = ((tmp_12[39] != 1'b0) || (tmp_12[38:30] == 9'b111111111) ? 9'b111111111 :
              tmp_12[38:30] + tmp_12[29]);

  assign scount_2 = scount_3 == 9'b100000000;

  assign scount_rateChange = scount_2;

  always @(posedge clk or posedge reset)
    begin : delayMatch_2_process
      if (reset == 1'b1) begin
        delayMatch_reg_2 <= {10{1'b0}};
      end
      else begin
        if (enb_1_8_0) begin
          delayMatch_reg_2[0] <= scount_rateChange;
          delayMatch_reg_2[32'sd9:32'sd1] <= delayMatch_reg_2[32'sd8:32'sd0];
        end
      end
    end

  assign scount_rateChange_1 = delayMatch_reg_2[9];

  assign j = 32'sd0;

  assign i = 32'sd0;

  // *(2^-8) = /256, shift
  // Choose wider type
  assign idx = 4'b0001;

  assign tmp_13 = 16'sb0000000000000000;

  // R(i,j) += x_i * conj(x_j)
  // scalar-only outer product:
  // scalar resets
  assign tmp_14 = 16'sb0000000000000000;

  assign sel = 1'b0;

  assign s_2 = 1'b1;

  assign sel_2 = (samp_valid == 1'b0 ? sel :
              s_2);

  assign tmp_15 = {8'b0, {tmp, 30'b000000000000000000000000000000}};

  assign s_3 = 40'h0040000000;

  assign adder_add_cast_4 = {1'b0, tmp_15};
  assign adder_add_cast_5 = {1'b0, s_3};
  assign adder_add_temp_2 = adder_add_cast_4 + adder_add_cast_5;
  assign tmp_16 = (adder_add_temp_2[40] != 1'b0 ? 40'hFFFFFFFFFF :
              adder_add_temp_2[39:0]);

  assign tmp_17 = {22'b0, tmp_16[39:30]};

  assign tmp_18 = tmp_17 - 32'sd1;

  always @(posedge clk or posedge reset)
    begin : buf_r_reg_process
      if (reset == 1'b1) begin
        for(buf_r_reg_t_1 = 32'sd0; buf_r_reg_t_1 <= 32'sd3; buf_r_reg_t_1 = buf_r_reg_t_1 + 32'sd1) begin
          buf_r_reg_reg[buf_r_reg_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb_1_80_0) begin
          for(buf_r_reg_t_0_1 = 32'sd0; buf_r_reg_t_0_1 <= 32'sd3; buf_r_reg_t_0_1 = buf_r_reg_t_0_1 + 32'sd1) begin
            buf_r_reg_reg[buf_r_reg_t_0_1] <= buf_r_reg_reg_next[buf_r_reg_t_0_1];
          end
        end
      end
    end
  genvar t_0_0;
  generate
    for(t_0_0 = 32'sd0; t_0_0 <= 32'sd3; t_0_0 = t_0_0 + 32'sd1) begin:buf_r_reg_reg_next_gen
      assign buf_r_1[t_0_0] = buf_r_reg_reg[t_0_0];
      assign buf_r_reg_reg_next[t_0_0] = buf_r[t_0_0];
    end
  endgenerate

  always @* begin

    for(p47buf_r_t_0 = 32'sd0; p47buf_r_t_0 <= 32'sd3; p47buf_r_t_0 = p47buf_r_t_0 + 32'sd1) begin
      buf_r[p47buf_r_t_0] = buf_r_1[p47buf_r_t_0];
    end

    if (sel_2) begin
      buf_r[tmp_18] = samp_re;
    end
  end

  assign sel_1 = 1'b0;

  assign s_4 = 1'b1;

  assign sel_2_1 = (samp_valid == 1'b0 ? sel_1 :
              s_4);

  assign tmp_19 = {8'b0, {tmp, 30'b000000000000000000000000000000}};

  assign s_5 = 40'h0040000000;

  assign adder_add_cast_6 = {1'b0, tmp_19};
  assign adder_add_cast_7 = {1'b0, s_5};
  assign adder_add_temp_3 = adder_add_cast_6 + adder_add_cast_7;
  assign tmp_20 = (adder_add_temp_3[40] != 1'b0 ? 40'hFFFFFFFFFF :
              adder_add_temp_3[39:0]);

  assign tmp_21 = {22'b0, tmp_20[39:30]};

  assign tmp_22 = tmp_21 - 32'sd1;

  always @(posedge clk or posedge reset)
    begin : buf_i_reg_process
      if (reset == 1'b1) begin
        for(buf_i_reg_t_1 = 32'sd0; buf_i_reg_t_1 <= 32'sd3; buf_i_reg_t_1 = buf_i_reg_t_1 + 32'sd1) begin
          buf_i_reg_reg[buf_i_reg_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb_1_80_0) begin
          for(buf_i_reg_t_0_1 = 32'sd0; buf_i_reg_t_0_1 <= 32'sd3; buf_i_reg_t_0_1 = buf_i_reg_t_0_1 + 32'sd1) begin
            buf_i_reg_reg[buf_i_reg_t_0_1] <= buf_i_reg_reg_next[buf_i_reg_t_0_1];
          end
        end
      end
    end
  genvar t_0_01;
  generate
    for(t_0_01 = 32'sd0; t_0_01 <= 32'sd3; t_0_01 = t_0_01 + 32'sd1) begin:buf_i_reg_reg_next_gen
      assign buf_i_1[t_0_01] = buf_i_reg_reg[t_0_01];
      assign buf_i_reg_reg_next[t_0_01] = buf_i[t_0_01];
    end
  endgenerate

  always @* begin

    for(p51buf_i_t_0 = 32'sd0; p51buf_i_t_0 <= 32'sd3; p51buf_i_t_0 = p51buf_i_t_0 + 32'sd1) begin
      buf_i[p51buf_i_t_0] = buf_i_1[p51buf_i_t_0];
    end

    if (sel_2_1) begin
      buf_i[tmp_22] = samp_im;
    end
  end

  generate
    genvar idx68;
    for(idx68 = 0; idx68 < 4; idx68 = idx68 + 1) begin : c135_tmp_gen1
      genvar idx67;
      for(idx67 = 0; idx67 < 4; idx67 = idx67 + 1) begin : c135_tmp_gen
        assign c135_tmp[idx67 + (idx68 * 4)] = tmp_23[idx67][idx68];
      end
    end
  endgenerate

  generate
    genvar idx66;
    for(idx66 = 0; idx66 < 4; idx66 = idx66 + 1) begin : c125_Rr_gen1
      genvar idx65;
      for(idx65 = 0; idx65 < 4; idx65 = idx65 + 1) begin : c125_Rr_gen
        assign c125_Rr[idx65 + (idx66 * 4)] = Rr[idx65][idx66];
      end
    end
  endgenerate

  generate
    genvar idx64;
    for(idx64 = 0; idx64 < 4; idx64 = idx64 + 1) begin : c125_tmp_gen1
      genvar idx63;
      for(idx63 = 0; idx63 < 4; idx63 = idx63 + 1) begin : c125_tmp_gen
        assign c125_tmp[idx63 + (idx64 * 4)] = tmp_23[idx63][idx64];
      end
    end
  endgenerate

  always @* begin
    if (tmp_4 == 1'b0) begin
      for(p37_t_1 = 32'sd0; p37_t_1 <= 32'sd15; p37_t_1 = p37_t_1 + 32'sd1) begin
        c125_tmp_1[p37_t_1] = c125_tmp[p37_t_1];
      end
    end
    else begin
      for(p37_t_0_0 = 32'sd0; p37_t_0_0 <= 32'sd15; p37_t_0_0 = p37_t_0_0 + 32'sd1) begin
        c125_tmp_1[p37_t_0_0] = c125_Rr[p37_t_0_0];
      end
    end
  end

  generate
    genvar idx62;
    for(idx62 = 0; idx62 < 4; idx62 = idx62 + 1) begin : tmp_24_gen1
      genvar idx61;
      for(idx61 = 0; idx61 < 4; idx61 = idx61 + 1) begin : tmp_24_gen
        assign tmp_24[idx61][idx62] = c125_tmp_1[idx61 + (idx62 * 4)];
      end
    end
  endgenerate

  generate
    genvar idx60;
    for(idx60 = 0; idx60 < 4; idx60 = idx60 + 1) begin : c126_tmp_gen1
      genvar idx59;
      for(idx59 = 0; idx59 < 4; idx59 = idx59 + 1) begin : c126_tmp_gen
        assign c126_tmp[idx59 + (idx60 * 4)] = tmp_24[idx59][idx60];
      end
    end
  endgenerate

  generate
    genvar idx58;
    for(idx58 = 0; idx58 < 4; idx58 = idx58 + 1) begin : Rr_1_gen1
      genvar idx57;
      for(idx57 = 0; idx57 < 4; idx57 = idx57 + 1) begin : Rr_1_gen
        assign Rr_1[idx57][idx58] = c133_Rr[idx57 + (idx58 * 4)];
      end
    end
  endgenerate

  generate
    genvar idx56;
    for(idx56 = 0; idx56 < 4; idx56 = idx56 + 1) begin : c124_Rr_gen1
      genvar idx55;
      for(idx55 = 0; idx55 < 4; idx55 = idx55 + 1) begin : c124_Rr_gen
        assign c124_Rr[idx55 + (idx56 * 4)] = Rr_1[idx55][idx56];
      end
    end
  endgenerate

  generate
    genvar idx54;
    for(idx54 = 0; idx54 < 4; idx54 = idx54 + 1) begin : c124_Rr_1_gen1
      genvar idx53;
      for(idx53 = 0; idx53 < 4; idx53 = idx53 + 1) begin : c124_Rr_1_gen
        assign c124_Rr_1[idx53 + (idx54 * 4)] = Rr_2[idx53][idx54];
      end
    end
  endgenerate

  always @* begin
    if (frame_start == 1'b0) begin
      for(p72_t_1 = 32'sd0; p72_t_1 <= 32'sd15; p72_t_1 = p72_t_1 + 32'sd1) begin
        c124_tmp[p72_t_1] = c124_Rr_1[p72_t_1];
      end
    end
    else begin
      for(p72_t_0_0 = 32'sd0; p72_t_0_0 <= 32'sd15; p72_t_0_0 = p72_t_0_0 + 32'sd1) begin
        c124_tmp[p72_t_0_0] = c124_Rr[p72_t_0_0];
      end
    end
  end

  generate
    genvar idx52;
    for(idx52 = 0; idx52 < 4; idx52 = idx52 + 1) begin : tmp_23_gen1
      genvar idx51;
      for(idx51 = 0; idx51 < 4; idx51 = idx51 + 1) begin : tmp_23_gen
        assign tmp_23[idx51][idx52] = c124_tmp[idx51 + (idx52 * 4)];
      end
    end
  endgenerate

  generate
    genvar idx50;
    for(idx50 = 0; idx50 < 4; idx50 = idx50 + 1) begin : c126_tmp_1_gen1
      genvar idx49;
      for(idx49 = 0; idx49 < 4; idx49 = idx49 + 1) begin : c126_tmp_1_gen
        assign c126_tmp_1[idx49 + (idx50 * 4)] = tmp_23[idx49][idx50];
      end
    end
  endgenerate

  always @* begin
    if (samp_valid == 1'b0) begin
      for(p31_t_1 = 32'sd0; p31_t_1 <= 32'sd15; p31_t_1 = p31_t_1 + 32'sd1) begin
        c126_tmp_2[p31_t_1] = c126_tmp_1[p31_t_1];
      end
    end
    else begin
      for(p31_t_0_0 = 32'sd0; p31_t_0_0 <= 32'sd15; p31_t_0_0 = p31_t_0_0 + 32'sd1) begin
        c126_tmp_2[p31_t_0_0] = c126_tmp[p31_t_0_0];
      end
    end
  end

  generate
    genvar idx48;
    for(idx48 = 0; idx48 < 4; idx48 = idx48 + 1) begin : tmp_25_gen1
      genvar idx47;
      for(idx47 = 0; idx47 < 4; idx47 = idx47 + 1) begin : tmp_25_gen
        assign tmp_25[idx47][idx48] = c126_tmp_2[idx47 + (idx48 * 4)];
      end
    end
  endgenerate

  generate
    genvar idx46;
    for(idx46 = 0; idx46 < 4; idx46 = idx46 + 1) begin : c128_tmp_gen1
      genvar idx45;
      for(idx45 = 0; idx45 < 4; idx45 = idx45 + 1) begin : c128_tmp_gen
        assign c128_tmp[idx45 + (idx46 * 4)] = tmp_25[idx45][idx46];
      end
    end
  endgenerate

  always @(posedge clk or posedge reset)
    begin : Rr_reg_process
      if (reset == 1'b1) begin
        for(Rr_reg_t_1 = 32'sd0; Rr_reg_t_1 <= 32'sd15; Rr_reg_t_1 = Rr_reg_t_1 + 32'sd1) begin
          Rr_reg_reg[Rr_reg_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb_1_80_0) begin
          for(Rr_reg_t_0_1 = 32'sd0; Rr_reg_t_0_1 <= 32'sd15; Rr_reg_t_0_1 = Rr_reg_t_0_1 + 32'sd1) begin
            Rr_reg_reg[Rr_reg_t_0_1] <= Rr_reg_reg_next[Rr_reg_t_0_1];
          end
        end
      end
    end
  genvar t_0_02;
  generate
    for(t_0_02 = 32'sd0; t_0_02 <= 32'sd15; t_0_02 = t_0_02 + 32'sd1) begin:Rr_reg_reg_next_gen
      assign c128_Rr[t_0_02] = Rr_reg_reg[t_0_02];
      assign Rr_reg_reg_next[t_0_02] = c128_tmp[t_0_02];
    end
  endgenerate

  generate
    genvar idx44;
    for(idx44 = 0; idx44 < 4; idx44 = idx44 + 1) begin : Rr_2_gen1
      genvar idx43;
      for(idx43 = 0; idx43 < 4; idx43 = idx43 + 1) begin : Rr_2_gen
        assign Rr_2[idx43][idx44] = c128_Rr[idx43 + (idx44 * 4)];
      end
    end
  endgenerate

  generate
    genvar idx42;
    for(idx42 = 0; idx42 < 4; idx42 = idx42 + 1) begin : c133_Rr_1_gen1
      genvar idx41;
      for(idx41 = 0; idx41 < 4; idx41 = idx41 + 1) begin : c133_Rr_1_gen
        assign c133_Rr_1[idx41 + (idx42 * 4)] = Rr_2[idx41][idx42];
      end
    end
  endgenerate

  generate
    genvar idx40;
    for(idx40 = 0; idx40 < 4; idx40 = idx40 + 1) begin : c133_Ri_gen1
      genvar idx39;
      for(idx39 = 0; idx39 < 4; idx39 = idx39 + 1) begin : c133_Ri_gen
        assign c133_Ri[idx39 + (idx40 * 4)] = Ri[idx39][idx40];
      end
    end
  endgenerate

  always @(tmp_13, tmp_14) begin
    p74_add_cast = 64'sh0000000000000000;
    p74_add_cast_0 = 64'sh0000000000000000;

    for(p74_i = 32'sd0; p74_i <= 32'sd3; p74_i = p74_i + 32'sd1) begin
      for(p74_j = 32'sd0; p74_j <= 32'sd3; p74_j = p74_j + 32'sd1) begin
        p74_add_cast = {{30{p74_j[31]}}, {p74_j, 2'b00}};
        p74_Rr[p74_i + p74_add_cast] = tmp_13;
        p74_add_cast_0 = {{30{p74_j[31]}}, {p74_j, 2'b00}};
        p74_Ri[p74_i + p74_add_cast_0] = tmp_14;
      end
    end
    for(p74_t_0 = 32'sd0; p74_t_0 <= 32'sd15; p74_t_0 = p74_t_0 + 32'sd1) begin
      c133_Ri_1[p74_t_0] = p74_Ri[p74_t_0];
      c133_Rr[p74_t_0] = p74_Rr[p74_t_0];
    end

  end

  generate
    genvar idx38;
    for(idx38 = 0; idx38 < 4; idx38 = idx38 + 1) begin : Ri_1_gen1
      genvar idx37;
      for(idx37 = 0; idx37 < 4; idx37 = idx37 + 1) begin : Ri_1_gen
        assign Ri_1[idx37][idx38] = c133_Ri_1[idx37 + (idx38 * 4)];
      end
    end
  endgenerate

  generate
    genvar idx36;
    for(idx36 = 0; idx36 < 4; idx36 = idx36 + 1) begin : c134_Ri_gen1
      genvar idx35;
      for(idx35 = 0; idx35 < 4; idx35 = idx35 + 1) begin : c134_Ri_gen
        assign c134_Ri[idx35 + (idx36 * 4)] = Ri_1[idx35][idx36];
      end
    end
  endgenerate

  generate
    genvar idx34;
    for(idx34 = 0; idx34 < 4; idx34 = idx34 + 1) begin : Ri_2_gen1
      genvar idx33;
      for(idx33 = 0; idx33 < 4; idx33 = idx33 + 1) begin : Ri_2_gen
        assign Ri_2[idx33][idx34] = c135_Ri[idx33 + (idx34 * 4)];
      end
    end
  endgenerate

  generate
    genvar idx32;
    for(idx32 = 0; idx32 < 4; idx32 = idx32 + 1) begin : c129_Ri_gen1
      genvar idx31;
      for(idx31 = 0; idx31 < 4; idx31 = idx31 + 1) begin : c129_Ri_gen
        assign c129_Ri[idx31 + (idx32 * 4)] = Ri_2[idx31][idx32];
      end
    end
  endgenerate

  generate
    genvar idx30;
    for(idx30 = 0; idx30 < 4; idx30 = idx30 + 1) begin : c129_tmp_gen1
      genvar idx29;
      for(idx29 = 0; idx29 < 4; idx29 = idx29 + 1) begin : c129_tmp_gen
        assign c129_tmp[idx29 + (idx30 * 4)] = tmp_26[idx29][idx30];
      end
    end
  endgenerate

  always @* begin
    if (tmp_4 == 1'b0) begin
      for(p38_t_1 = 32'sd0; p38_t_1 <= 32'sd15; p38_t_1 = p38_t_1 + 32'sd1) begin
        c129_tmp_1[p38_t_1] = c129_tmp[p38_t_1];
      end
    end
    else begin
      for(p38_t_0_0 = 32'sd0; p38_t_0_0 <= 32'sd15; p38_t_0_0 = p38_t_0_0 + 32'sd1) begin
        c129_tmp_1[p38_t_0_0] = c129_Ri[p38_t_0_0];
      end
    end
  end

  generate
    genvar idx28;
    for(idx28 = 0; idx28 < 4; idx28 = idx28 + 1) begin : tmp_27_gen1
      genvar idx27;
      for(idx27 = 0; idx27 < 4; idx27 = idx27 + 1) begin : tmp_27_gen
        assign tmp_27[idx27][idx28] = c129_tmp_1[idx27 + (idx28 * 4)];
      end
    end
  endgenerate

  generate
    genvar idx26;
    for(idx26 = 0; idx26 < 4; idx26 = idx26 + 1) begin : c130_tmp_gen1
      genvar idx25;
      for(idx25 = 0; idx25 < 4; idx25 = idx25 + 1) begin : c130_tmp_gen
        assign c130_tmp[idx25 + (idx26 * 4)] = tmp_27[idx25][idx26];
      end
    end
  endgenerate

  generate
    genvar idx24;
    for(idx24 = 0; idx24 < 4; idx24 = idx24 + 1) begin : c130_tmp_1_gen1
      genvar idx23;
      for(idx23 = 0; idx23 < 4; idx23 = idx23 + 1) begin : c130_tmp_1_gen
        assign c130_tmp_1[idx23 + (idx24 * 4)] = tmp_26[idx23][idx24];
      end
    end
  endgenerate

  always @* begin
    if (samp_valid == 1'b0) begin
      for(p33_t_1 = 32'sd0; p33_t_1 <= 32'sd15; p33_t_1 = p33_t_1 + 32'sd1) begin
        c130_tmp_2[p33_t_1] = c130_tmp_1[p33_t_1];
      end
    end
    else begin
      for(p33_t_0_0 = 32'sd0; p33_t_0_0 <= 32'sd15; p33_t_0_0 = p33_t_0_0 + 32'sd1) begin
        c130_tmp_2[p33_t_0_0] = c130_tmp[p33_t_0_0];
      end
    end
  end

  generate
    genvar idx22;
    for(idx22 = 0; idx22 < 4; idx22 = idx22 + 1) begin : tmp_28_gen1
      genvar idx21;
      for(idx21 = 0; idx21 < 4; idx21 = idx21 + 1) begin : tmp_28_gen
        assign tmp_28[idx21][idx22] = c130_tmp_2[idx21 + (idx22 * 4)];
      end
    end
  endgenerate

  generate
    genvar idx20;
    for(idx20 = 0; idx20 < 4; idx20 = idx20 + 1) begin : c132_tmp_gen1
      genvar idx19;
      for(idx19 = 0; idx19 < 4; idx19 = idx19 + 1) begin : c132_tmp_gen
        assign c132_tmp[idx19 + (idx20 * 4)] = tmp_28[idx19][idx20];
      end
    end
  endgenerate

  always @(posedge clk or posedge reset)
    begin : Ri_reg_process
      if (reset == 1'b1) begin
        for(Ri_reg_t_1 = 32'sd0; Ri_reg_t_1 <= 32'sd15; Ri_reg_t_1 = Ri_reg_t_1 + 32'sd1) begin
          Ri_reg_reg[Ri_reg_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb_1_80_0) begin
          for(Ri_reg_t_0_1 = 32'sd0; Ri_reg_t_0_1 <= 32'sd15; Ri_reg_t_0_1 = Ri_reg_t_0_1 + 32'sd1) begin
            Ri_reg_reg[Ri_reg_t_0_1] <= Ri_reg_reg_next[Ri_reg_t_0_1];
          end
        end
      end
    end
  genvar t_0_03;
  generate
    for(t_0_03 = 32'sd0; t_0_03 <= 32'sd15; t_0_03 = t_0_03 + 32'sd1) begin:Ri_reg_reg_next_gen
      assign c132_Ri[t_0_03] = Ri_reg_reg[t_0_03];
      assign Ri_reg_reg_next[t_0_03] = c132_tmp[t_0_03];
    end
  endgenerate

  generate
    genvar idx18;
    for(idx18 = 0; idx18 < 4; idx18 = idx18 + 1) begin : Ri_gen1
      genvar idx17;
      for(idx17 = 0; idx17 < 4; idx17 = idx17 + 1) begin : Ri_gen
        assign Ri[idx17][idx18] = c132_Ri[idx17 + (idx18 * 4)];
      end
    end
  endgenerate

  generate
    genvar idx16;
    for(idx16 = 0; idx16 < 4; idx16 = idx16 + 1) begin : c134_Ri_1_gen1
      genvar idx15;
      for(idx15 = 0; idx15 < 4; idx15 = idx15 + 1) begin : c134_Ri_1_gen
        assign c134_Ri_1[idx15 + (idx16 * 4)] = Ri[idx15][idx16];
      end
    end
  endgenerate

  always @* begin
    if (frame_start == 1'b0) begin
      for(p73_t_1 = 32'sd0; p73_t_1 <= 32'sd15; p73_t_1 = p73_t_1 + 32'sd1) begin
        c134_tmp[p73_t_1] = c134_Ri_1[p73_t_1];
      end
    end
    else begin
      for(p73_t_0_0 = 32'sd0; p73_t_0_0 <= 32'sd15; p73_t_0_0 = p73_t_0_0 + 32'sd1) begin
        c134_tmp[p73_t_0_0] = c134_Ri[p73_t_0_0];
      end
    end
  end

  generate
    genvar idx14;
    for(idx14 = 0; idx14 < 4; idx14 = idx14 + 1) begin : tmp_26_gen1
      genvar idx13;
      for(idx13 = 0; idx13 < 4; idx13 = idx13 + 1) begin : tmp_26_gen
        assign tmp_26[idx13][idx14] = c134_tmp[idx13 + (idx14 * 4)];
      end
    end
  endgenerate

  generate
    genvar idx12;
    for(idx12 = 0; idx12 < 4; idx12 = idx12 + 1) begin : c135_tmp_1_gen1
      genvar idx11;
      for(idx11 = 0; idx11 < 4; idx11 = idx11 + 1) begin : c135_tmp_1_gen
        assign c135_tmp_1[idx11 + (idx12 * 4)] = tmp_26[idx11][idx12];
      end
    end
  endgenerate

  always @* begin
    p46_mul_temp = 32'sb00000000000000000000000000000000;
    p46_mul_temp_0 = 32'sb00000000000000000000000000000000;
    p46_add_temp = 40'sh0000000000;
    p46_add_temp_0 = 41'sh00000000000;
    p46_mul_temp_1 = 32'sb00000000000000000000000000000000;
    p46_mul_temp_2 = 32'sb00000000000000000000000000000000;
    p46_sub_temp = 40'sh0000000000;
    p46_add_temp_1 = 41'sh00000000000;
    p46_add_cast = 64'sh0000000000000000;
    p46_add_cast_0 = 64'sh0000000000000000;
    p46_add_cast_1 = 40'sh0000000000;
    p46_add_cast_2 = 41'sh00000000000;
    p46_add_cast_3 = 40'sh0000000000;
    p46_add_cast_4 = 40'sh0000000000;
    p46_add_cast_5 = 41'sh00000000000;
    p46_cast = 40'sh0000000000;
    p46_add_cast_6 = 64'sh0000000000000000;
    p46_add_cast_7 = 64'sh0000000000000000;
    p46_add_cast_8 = 40'sh0000000000;
    p46_add_cast_9 = 41'sh00000000000;
    p46_sub_cast = 40'sh0000000000;
    p46_sub_cast_0 = 40'sh0000000000;
    p46_add_cast_10 = 41'sh00000000000;
    p46_cast_0 = 40'sh0000000000;

    for(p46_t_0 = 32'sd0; p46_t_0 <= 32'sd15; p46_t_0 = p46_t_0 + 32'sd1) begin
      p46_Ri[p46_t_0] = c135_tmp_1[p46_t_0];
      p46_Rr[p46_t_0] = c135_tmp[p46_t_0];
    end
    for(p46_i = 32'sd0; p46_i <= 32'sd3; p46_i = p46_i + 32'sd1) begin
      for(p46_j = 32'sd0; p46_j <= 32'sd3; p46_j = p46_j + 32'sd1) begin
        p46_add_cast = {{30{p46_j[31]}}, {p46_j, 2'b00}};
        p46_add_cast_0 = {{30{p46_j[31]}}, {p46_j, 2'b00}};
        p46_add_cast_1 = {p46_Rr[p46_i + p46_add_cast_0], 24'b000000000000000000000000};
        p46_add_cast_2 = {p46_add_cast_1[39], p46_add_cast_1};
        p46_mul_temp = buf_r[p46_i] * buf_r[p46_j];
        p46_add_cast_3 = {{4{p46_mul_temp[31]}}, {p46_mul_temp, 4'b0000}};
        p46_mul_temp_0 = buf_i[p46_i] * buf_i[p46_j];
        p46_add_cast_4 = {{4{p46_mul_temp_0[31]}}, {p46_mul_temp_0, 4'b0000}};
        p46_add_temp = p46_add_cast_3 + p46_add_cast_4;
        p46_add_cast_5 = {p46_add_temp[39], p46_add_temp};
        p46_add_temp_0 = p46_add_cast_2 + p46_add_cast_5;
        if ((p46_add_temp_0[40] == 1'b0) && (p46_add_temp_0[39] != 1'b0)) begin
          p46_cast = 40'sh7FFFFFFFFF;
        end
        else if ((p46_add_temp_0[40] == 1'b1) && (p46_add_temp_0[39] != 1'b1)) begin
          p46_cast = 40'sh8000000000;
        end
        else begin
          p46_cast = p46_add_temp_0[39:0];
        end
        if ((p46_cast[39] == 1'b0) && (p46_cast[38:24] == 15'b111111111111111)) begin
          p46_Rr[p46_i + p46_add_cast] = 16'sb0111111111111111;
        end
        else begin
          p46_Rr[p46_i + p46_add_cast] = p46_cast[39:24] + $signed({1'b0, p46_cast[23]});
        end
        p46_add_cast_6 = {{30{p46_j[31]}}, {p46_j, 2'b00}};
        p46_add_cast_7 = {{30{p46_j[31]}}, {p46_j, 2'b00}};
        p46_add_cast_8 = {p46_Ri[p46_i + p46_add_cast_7], 24'b000000000000000000000000};
        p46_add_cast_9 = {p46_add_cast_8[39], p46_add_cast_8};
        p46_mul_temp_1 = buf_i[p46_i] * buf_r[p46_j];
        p46_sub_cast = {{4{p46_mul_temp_1[31]}}, {p46_mul_temp_1, 4'b0000}};
        p46_mul_temp_2 = buf_r[p46_i] * buf_i[p46_j];
        p46_sub_cast_0 = {{4{p46_mul_temp_2[31]}}, {p46_mul_temp_2, 4'b0000}};
        p46_sub_temp = p46_sub_cast - p46_sub_cast_0;
        p46_add_cast_10 = {p46_sub_temp[39], p46_sub_temp};
        p46_add_temp_1 = p46_add_cast_9 + p46_add_cast_10;
        if ((p46_add_temp_1[40] == 1'b0) && (p46_add_temp_1[39] != 1'b0)) begin
          p46_cast_0 = 40'sh7FFFFFFFFF;
        end
        else if ((p46_add_temp_1[40] == 1'b1) && (p46_add_temp_1[39] != 1'b1)) begin
          p46_cast_0 = 40'sh8000000000;
        end
        else begin
          p46_cast_0 = p46_add_temp_1[39:0];
        end
        if ((p46_cast_0[39] == 1'b0) && (p46_cast_0[38:24] == 15'b111111111111111)) begin
          p46_Ri[p46_i + p46_add_cast_6] = 16'sb0111111111111111;
        end
        else begin
          p46_Ri[p46_i + p46_add_cast_6] = p46_cast_0[39:24] + $signed({1'b0, p46_cast_0[23]});
        end
      end
    end
    for(p46_t_1 = 32'sd0; p46_t_1 <= 32'sd15; p46_t_1 = p46_t_1 + 32'sd1) begin
      c135_Ri[p46_t_1] = p46_Ri[p46_t_1];
      c135_Rr[p46_t_1] = p46_Rr[p46_t_1];
    end

  end

  generate
    genvar idx10;
    for(idx10 = 0; idx10 < 4; idx10 = idx10 + 1) begin : Rr_gen1
      genvar idx9;
      for(idx9 = 0; idx9 < 4; idx9 = idx9 + 1) begin : Rr_gen
        assign Rr[idx9][idx10] = c135_Rr[idx9 + (idx10 * 4)];
      end
    end
  endgenerate

  generate
    genvar idx8;
    for(idx8 = 0; idx8 < 4; idx8 = idx8 + 1) begin : c181_Rr_gen1
      genvar idx7;
      for(idx7 = 0; idx7 < 4; idx7 = idx7 + 1) begin : c181_Rr_gen
        assign c181_Rr[idx7 + (idx8 * 4)] = Rr[idx7][idx8];
      end
    end
  endgenerate

  assign c181_Rr_1[0] = c181_Rr[0];
  assign c181_Rr_1[1] = c181_Rr[1];
  assign c181_Rr_1[2] = c181_Rr[2];
  assign c181_Rr_1[3] = c181_Rr[3];
  assign c181_Rr_1[4] = c181_Rr[4];
  assign c181_Rr_1[5] = c181_Rr[5];
  assign c181_Rr_1[6] = c181_Rr[6];
  assign c181_Rr_1[7] = c181_Rr[7];
  assign c181_Rr_1[8] = c181_Rr[8];
  assign c181_Rr_1[9] = c181_Rr[9];
  assign c181_Rr_1[10] = c181_Rr[10];
  assign c181_Rr_1[11] = c181_Rr[11];
  assign c181_Rr_1[12] = c181_Rr[12];
  assign c181_Rr_1[13] = c181_Rr[13];
  assign c181_Rr_1[14] = c181_Rr[14];
  assign c181_Rr_1[15] = c181_Rr[15];

  generate
    genvar idx6;
    for(idx6 = 0; idx6 < 4; idx6 = idx6 + 1) begin : Rr_3_gen1
      genvar idx5;
      for(idx5 = 0; idx5 < 4; idx5 = idx5 + 1) begin : Rr_3_gen
        assign Rr_3[idx5][idx6] = c181_Rr_1[idx5 + (idx6 * 4)];
      end
    end
  endgenerate

  generate
    genvar idx4;
    for(idx4 = 0; idx4 < 4; idx4 = idx4 + 1) begin : c182_Ri_gen1
      genvar idx3;
      for(idx3 = 0; idx3 < 4; idx3 = idx3 + 1) begin : c182_Ri_gen
        assign c182_Ri[idx3 + (idx4 * 4)] = Ri_2[idx3][idx4];
      end
    end
  endgenerate

  assign c182_Ri_1[0] = c182_Ri[0];
  assign c182_Ri_1[1] = c182_Ri[1];
  assign c182_Ri_1[2] = c182_Ri[2];
  assign c182_Ri_1[3] = c182_Ri[3];
  assign c182_Ri_1[4] = c182_Ri[4];
  assign c182_Ri_1[5] = c182_Ri[5];
  assign c182_Ri_1[6] = c182_Ri[6];
  assign c182_Ri_1[7] = c182_Ri[7];
  assign c182_Ri_1[8] = c182_Ri[8];
  assign c182_Ri_1[9] = c182_Ri[9];
  assign c182_Ri_1[10] = c182_Ri[10];
  assign c182_Ri_1[11] = c182_Ri[11];
  assign c182_Ri_1[12] = c182_Ri[12];
  assign c182_Ri_1[13] = c182_Ri[13];
  assign c182_Ri_1[14] = c182_Ri[14];
  assign c182_Ri_1[15] = c182_Ri[15];

  generate
    genvar idx2;
    for(idx2 = 0; idx2 < 4; idx2 = idx2 + 1) begin : Ri_3_gen1
      genvar idx1;
      for(idx1 = 0; idx1 < 4; idx1 = idx1 + 1) begin : Ri_3_gen
        assign Ri_3[idx1][idx2] = c182_Ri_1[idx1 + (idx2 * 4)];
      end
    end
  endgenerate

  assign enbSig_1 = 1'b1;

  covariance_core_fixptp44 u_covariance_core_fixptp44 (.clk(clk),
                                                       .reset(reset),
                                                       .enb_1_5_0(enb_1_5_0),
                                                       .j(j),  // int32
                                                       .i(i),  // int32
                                                       .idx(idx),  // ufix4
                                                       .Rtri_re_0(Rtri_re[0]),  // sfix16_En14
                                                       .Rtri_re_1(Rtri_re[1]),  // sfix16_En14
                                                       .Rtri_re_2(Rtri_re[2]),  // sfix16_En14
                                                       .Rtri_re_3(Rtri_re[3]),  // sfix16_En14
                                                       .Rtri_re_4(Rtri_re[4]),  // sfix16_En14
                                                       .Rtri_re_5(Rtri_re[5]),  // sfix16_En14
                                                       .Rtri_re_6(Rtri_re[6]),  // sfix16_En14
                                                       .Rtri_re_7(Rtri_re[7]),  // sfix16_En14
                                                       .Rtri_re_8(Rtri_re[8]),  // sfix16_En14
                                                       .Rtri_re_9(Rtri_re[9]),  // sfix16_En14
                                                       .Rtri_im_0(Rtri_im[0]),  // sfix16_En14
                                                       .Rtri_im_1(Rtri_im[1]),  // sfix16_En14
                                                       .Rtri_im_2(Rtri_im[2]),  // sfix16_En14
                                                       .Rtri_im_3(Rtri_im[3]),  // sfix16_En14
                                                       .Rtri_im_4(Rtri_im[4]),  // sfix16_En14
                                                       .Rtri_im_5(Rtri_im[5]),  // sfix16_En14
                                                       .Rtri_im_6(Rtri_im[6]),  // sfix16_En14
                                                       .Rtri_im_7(Rtri_im[7]),  // sfix16_En14
                                                       .Rtri_im_8(Rtri_im[8]),  // sfix16_En14
                                                       .Rtri_im_9(Rtri_im[9]),  // sfix16_En14
                                                       .Rr_0(Rr_3[0][0]),  // sfix16_En6
                                                       .Rr_1(Rr_3[1][0]),  // sfix16_En6
                                                       .Rr_2(Rr_3[2][0]),  // sfix16_En6
                                                       .Rr_3(Rr_3[3][0]),  // sfix16_En6
                                                       .Rr_4(Rr_3[0][1]),  // sfix16_En6
                                                       .Rr_5(Rr_3[1][1]),  // sfix16_En6
                                                       .Rr_6(Rr_3[2][1]),  // sfix16_En6
                                                       .Rr_7(Rr_3[3][1]),  // sfix16_En6
                                                       .Rr_8(Rr_3[0][2]),  // sfix16_En6
                                                       .Rr_9(Rr_3[1][2]),  // sfix16_En6
                                                       .Rr_10(Rr_3[2][2]),  // sfix16_En6
                                                       .Rr_11(Rr_3[3][2]),  // sfix16_En6
                                                       .Rr_12(Rr_3[0][3]),  // sfix16_En6
                                                       .Rr_13(Rr_3[1][3]),  // sfix16_En6
                                                       .Rr_14(Rr_3[2][3]),  // sfix16_En6
                                                       .Rr_15(Rr_3[3][3]),  // sfix16_En6
                                                       .Ri_0(Ri_3[0][0]),  // sfix16_En6
                                                       .Ri_1(Ri_3[1][0]),  // sfix16_En6
                                                       .Ri_2(Ri_3[2][0]),  // sfix16_En6
                                                       .Ri_3(Ri_3[3][0]),  // sfix16_En6
                                                       .Ri_4(Ri_3[0][1]),  // sfix16_En6
                                                       .Ri_5(Ri_3[1][1]),  // sfix16_En6
                                                       .Ri_6(Ri_3[2][1]),  // sfix16_En6
                                                       .Ri_7(Ri_3[3][1]),  // sfix16_En6
                                                       .Ri_8(Ri_3[0][2]),  // sfix16_En6
                                                       .Ri_9(Ri_3[1][2]),  // sfix16_En6
                                                       .Ri_10(Ri_3[2][2]),  // sfix16_En6
                                                       .Ri_11(Ri_3[3][2]),  // sfix16_En6
                                                       .Ri_12(Ri_3[0][3]),  // sfix16_En6
                                                       .Ri_13(Ri_3[1][3]),  // sfix16_En6
                                                       .Ri_14(Ri_3[2][3]),  // sfix16_En6
                                                       .Ri_15(Ri_3[3][3]),  // sfix16_En6
                                                       .enb(enbSig_1),
                                                       .Rtri_re_0_1(Rtri_re_0_1),  // sfix16_En14
                                                       .Rtri_re_1_1(Rtri_re_1_1),  // sfix16_En14
                                                       .Rtri_re_2_1(Rtri_re_2_1),  // sfix16_En14
                                                       .Rtri_re_3_1(Rtri_re_3_1),  // sfix16_En14
                                                       .Rtri_re_4_1(Rtri_re_4_1),  // sfix16_En14
                                                       .Rtri_re_5_1(Rtri_re_5_1),  // sfix16_En14
                                                       .Rtri_re_6_1(Rtri_re_6_1),  // sfix16_En14
                                                       .Rtri_re_7_1(Rtri_re_7_1),  // sfix16_En14
                                                       .Rtri_re_8_1(Rtri_re_8_1),  // sfix16_En14
                                                       .Rtri_re_9_1(Rtri_re_9_1),  // sfix16_En14
                                                       .Rtri_im_0_1(Rtri_im_0_1),  // sfix16_En14
                                                       .Rtri_im_1_1(Rtri_im_1_1),  // sfix16_En14
                                                       .Rtri_im_2_1(Rtri_im_2_1),  // sfix16_En14
                                                       .Rtri_im_3_1(Rtri_im_3_1),  // sfix16_En14
                                                       .Rtri_im_4_1(Rtri_im_4_1),  // sfix16_En14
                                                       .Rtri_im_5_1(Rtri_im_5_1),  // sfix16_En14
                                                       .Rtri_im_6_1(Rtri_im_6_1),  // sfix16_En14
                                                       .Rtri_im_7_1(Rtri_im_7_1),  // sfix16_En14
                                                       .Rtri_im_8_1(Rtri_im_8_1),  // sfix16_En14
                                                       .Rtri_im_9_1(Rtri_im_9_1)  // sfix16_En14
                                                       );

  assign Rtri_re_10[0] = Rtri_re_0_1;
  assign Rtri_re_10[1] = Rtri_re_1_1;
  assign Rtri_re_10[2] = Rtri_re_2_1;
  assign Rtri_re_10[3] = Rtri_re_3_1;
  assign Rtri_re_10[4] = Rtri_re_4_1;
  assign Rtri_re_10[5] = Rtri_re_5_1;
  assign Rtri_re_10[6] = Rtri_re_6_1;
  assign Rtri_re_10[7] = Rtri_re_7_1;
  assign Rtri_re_10[8] = Rtri_re_8_1;
  assign Rtri_re_10[9] = Rtri_re_9_1;

  assign Rtri_im_10[0] = Rtri_im_0_1;
  assign Rtri_im_10[1] = Rtri_im_1_1;
  assign Rtri_im_10[2] = Rtri_im_2_1;
  assign Rtri_im_10[3] = Rtri_im_3_1;
  assign Rtri_im_10[4] = Rtri_im_4_1;
  assign Rtri_im_10[5] = Rtri_im_5_1;
  assign Rtri_im_10[6] = Rtri_im_6_1;
  assign Rtri_im_10[7] = Rtri_im_7_1;
  assign Rtri_im_10[8] = Rtri_im_8_1;
  assign Rtri_im_10[9] = Rtri_im_9_1;

  always @(posedge clk or posedge reset)
    begin : Rtri_downsample_bypass_process
      if (reset == 1'b1) begin
        for(Rtri_downsample_bypass_t_1_0 = 32'sd0; Rtri_downsample_bypass_t_1_0 <= 32'sd9; Rtri_downsample_bypass_t_1_0 = Rtri_downsample_bypass_t_1_0 + 32'sd1) begin
          Rtri_downsample_bypass_reg_re[Rtri_downsample_bypass_t_1_0] <= 16'sb0000000000000000;
          Rtri_downsample_bypass_reg_im[Rtri_downsample_bypass_t_1_0] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb_1_80_1) begin
          for(Rtri_downsample_bypass_t_0_0 = 32'sd0; Rtri_downsample_bypass_t_0_0 <= 32'sd9; Rtri_downsample_bypass_t_0_0 = Rtri_downsample_bypass_t_0_0 + 32'sd1) begin
            Rtri_downsample_bypass_reg_re[Rtri_downsample_bypass_t_0_0] <= Rtri_downsample_bypass_reg_next_re[Rtri_downsample_bypass_t_0_0];
            Rtri_downsample_bypass_reg_im[Rtri_downsample_bypass_t_0_0] <= Rtri_downsample_bypass_reg_next_im[Rtri_downsample_bypass_t_0_0];
          end
        end
      end
    end

  always @* begin
    if (enb_1_80_1 == 1'b1) begin
      for(Rtri_downsample_bypass_t_1 = 32'sd0; Rtri_downsample_bypass_t_1 <= 32'sd9; Rtri_downsample_bypass_t_1 = Rtri_downsample_bypass_t_1 + 32'sd1) begin
        Rtri_re_11[Rtri_downsample_bypass_t_1] = Rtri_re_10[Rtri_downsample_bypass_t_1];
        Rtri_im_11[Rtri_downsample_bypass_t_1] = Rtri_im_10[Rtri_downsample_bypass_t_1];
      end
    end
    else begin
      for(Rtri_downsample_bypass_t_0 = 32'sd0; Rtri_downsample_bypass_t_0 <= 32'sd9; Rtri_downsample_bypass_t_0 = Rtri_downsample_bypass_t_0 + 32'sd1) begin
        Rtri_re_11[Rtri_downsample_bypass_t_0] = Rtri_downsample_bypass_reg_re[Rtri_downsample_bypass_t_0];
        Rtri_im_11[Rtri_downsample_bypass_t_0] = Rtri_downsample_bypass_reg_im[Rtri_downsample_bypass_t_0];
      end
    end

    for(Rtri_downsample_bypass_t_2 = 32'sd0; Rtri_downsample_bypass_t_2 <= 32'sd9; Rtri_downsample_bypass_t_2 = Rtri_downsample_bypass_t_2 + 32'sd1) begin
      Rtri_downsample_bypass_reg_next_re[Rtri_downsample_bypass_t_2] = Rtri_re_10[Rtri_downsample_bypass_t_2];
      Rtri_downsample_bypass_reg_next_im[Rtri_downsample_bypass_t_2] = Rtri_im_10[Rtri_downsample_bypass_t_2];
    end

  end

  assign ratechange_splitcomp_out0_re_1 = Rtri_re_11[0];

  assign ratechange_splitcomp_out0_im_1 = Rtri_im_11[0];

  assign ratechange_splitcomp_out1_re_1 = Rtri_re_11[1];

  assign ratechange_splitcomp_out1_im_1 = Rtri_im_11[1];

  assign ratechange_splitcomp_out2_re_1 = Rtri_re_11[2];

  assign ratechange_splitcomp_out2_im_1 = Rtri_im_11[2];

  assign ratechange_splitcomp_out3_re_1 = Rtri_re_11[3];

  assign ratechange_splitcomp_out3_im_1 = Rtri_im_11[3];

  assign ratechange_splitcomp_out4_re_1 = Rtri_re_11[4];

  assign ratechange_splitcomp_out4_im_1 = Rtri_im_11[4];

  assign ratechange_splitcomp_out5_re_1 = Rtri_re_11[5];

  assign ratechange_splitcomp_out5_im_1 = Rtri_im_11[5];

  assign ratechange_splitcomp_out6_re_1 = Rtri_re_11[6];

  assign ratechange_splitcomp_out6_im_1 = Rtri_im_11[6];

  assign ratechange_splitcomp_out7_re_1 = Rtri_re_11[7];

  assign ratechange_splitcomp_out7_im_1 = Rtri_im_11[7];

  assign ratechange_splitcomp_out8_re_1 = Rtri_re_11[8];

  assign ratechange_splitcomp_out8_im_1 = Rtri_im_11[8];

  assign ratechange_splitcomp_out9_re_1 = Rtri_re_11[9];

  assign ratechange_splitcomp_out9_im_1 = Rtri_im_11[9];

  assign Rtri_serializer_re_2 = (counterSig == 4'b0000 ? ratechange_splitcomp_out0_re_1 :
              (counterSig == 4'b0001 ? ratechange_splitcomp_out1_re_1 :
              (counterSig == 4'b0010 ? ratechange_splitcomp_out2_re_1 :
              (counterSig == 4'b0011 ? ratechange_splitcomp_out3_re_1 :
              (counterSig == 4'b0100 ? ratechange_splitcomp_out4_re_1 :
              (counterSig == 4'b0101 ? ratechange_splitcomp_out5_re_1 :
              (counterSig == 4'b0110 ? ratechange_splitcomp_out6_re_1 :
              (counterSig == 4'b0111 ? ratechange_splitcomp_out7_re_1 :
              (counterSig == 4'b1000 ? ratechange_splitcomp_out8_re_1 :
              ratechange_splitcomp_out9_re_1)))))))));
  assign Rtri_serializer_im_2 = (counterSig == 4'b0000 ? ratechange_splitcomp_out0_im_1 :
              (counterSig == 4'b0001 ? ratechange_splitcomp_out1_im_1 :
              (counterSig == 4'b0010 ? ratechange_splitcomp_out2_im_1 :
              (counterSig == 4'b0011 ? ratechange_splitcomp_out3_im_1 :
              (counterSig == 4'b0100 ? ratechange_splitcomp_out4_im_1 :
              (counterSig == 4'b0101 ? ratechange_splitcomp_out5_im_1 :
              (counterSig == 4'b0110 ? ratechange_splitcomp_out6_im_1 :
              (counterSig == 4'b0111 ? ratechange_splitcomp_out7_im_1 :
              (counterSig == 4'b1000 ? ratechange_splitcomp_out8_im_1 :
              ratechange_splitcomp_out9_im_1)))))))));

  assign tmp_re = (scount_rateChange_1 == 1'b0 ? Rtri_serializer_re_1 :
              Rtri_serializer_re_2);
  assign tmp_im = (scount_rateChange_1 == 1'b0 ? Rtri_serializer_im_1 :
              Rtri_serializer_im_2);

  assign tmp_re_1 = (tmp_rateChange_1 == 1'b0 ? Rtri_serializer_re_1 :
              tmp_re);
  assign tmp_im_1 = (tmp_rateChange_1 == 1'b0 ? Rtri_serializer_im_1 :
              tmp_im);

  assign tmp_re_2 = (samp_valid_rateChange_1 == 1'b0 ? Rtri_serializer_re_1 :
              tmp_re_1);
  assign tmp_im_2 = (samp_valid_rateChange_1 == 1'b0 ? Rtri_serializer_im_1 :
              tmp_im_1);

  always @(posedge clk or posedge reset)
    begin : tapped_delay_process
      if (reset == 1'b1) begin
        for(tapped_delay_t_1_0 = 32'sd0; tapped_delay_t_1_0 <= 32'sd8; tapped_delay_t_1_0 = tapped_delay_t_1_0 + 32'sd1) begin
          tapped_delay_reg_re[tapped_delay_t_1_0] <= 16'sb0000000000000000;
          tapped_delay_reg_im[tapped_delay_t_1_0] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb_1_8_0) begin
          for(tapped_delay_t_0_1 = 32'sd0; tapped_delay_t_0_1 <= 32'sd8; tapped_delay_t_0_1 = tapped_delay_t_0_1 + 32'sd1) begin
            tapped_delay_reg_re[tapped_delay_t_0_1] <= tapped_delay_reg_next_re[tapped_delay_t_0_1];
            tapped_delay_reg_im[tapped_delay_t_0_1] <= tapped_delay_reg_next_im[tapped_delay_t_0_1];
          end
        end
      end
    end

  always @* begin

    for(tapped_delay_t_0_0 = 32'sd0; tapped_delay_t_0_0 <= 32'sd8; tapped_delay_t_0_0 = tapped_delay_t_0_0 + 32'sd1) begin
      tappedDelaySig_re[tapped_delay_t_0_0] = tapped_delay_reg_re[tapped_delay_t_0_0];
      tappedDelaySig_im[tapped_delay_t_0_0] = tapped_delay_reg_im[tapped_delay_t_0_0];
    end

    tappedDelaySig_re[9] = tmp_re_2;
    tappedDelaySig_im[9] = tmp_im_2;

    for(tapped_delay_t_1 = 32'sd0; tapped_delay_t_1 <= 32'sd7; tapped_delay_t_1 = tapped_delay_t_1 + 32'sd1) begin
      tapped_delay_reg_next_re[tapped_delay_t_1] = tapped_delay_reg_re[32'sd1 + tapped_delay_t_1];
      tapped_delay_reg_next_im[tapped_delay_t_1] = tapped_delay_reg_im[32'sd1 + tapped_delay_t_1];
    end

    tapped_delay_reg_next_re[8] = tmp_re_2;
    tapped_delay_reg_next_im[8] = tmp_im_2;
  end

  always @(posedge clk or posedge reset)
    begin : unit_delay_process
      if (reset == 1'b1) begin
        for(unit_delay_t_1 = 32'sd0; unit_delay_t_1 <= 32'sd9; unit_delay_t_1 = unit_delay_t_1 + 32'sd1) begin
          unit_delay_reg_re[unit_delay_t_1] <= 16'sb0000000000000000;
          unit_delay_reg_im[unit_delay_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb_1_8_0 && compareSig) begin
          for(unit_delay_t_0_0 = 32'sd0; unit_delay_t_0_0 <= 32'sd9; unit_delay_t_0_0 = unit_delay_t_0_0 + 32'sd1) begin
            unit_delay_reg_re[unit_delay_t_0_0] <= unit_delay_reg_next_re[unit_delay_t_0_0];
            unit_delay_reg_im[unit_delay_t_0_0] <= unit_delay_reg_next_im[unit_delay_t_0_0];
          end
        end
      end
    end
  genvar t_01;
  generate
    for(t_01 = 32'sd0; t_01 <= 32'sd9; t_01 = t_01 + 32'sd1) begin:unit_delay_reg_next_im_gen
      assign unitDelaySig_re[t_01] = unit_delay_reg_re[t_01];
      assign unitDelaySig_im[t_01] = unit_delay_reg_im[t_01];
      assign unit_delay_reg_next_re[t_01] = tappedDelaySig_re[t_01];
      assign unit_delay_reg_next_im[t_01] = tappedDelaySig_im[t_01];
    end
  endgenerate

  assign Rtri_re_0 = unitDelaySig_re[0];

  assign Rtri_re_1 = unitDelaySig_re[1];

  assign Rtri_re_2 = unitDelaySig_re[2];

  assign Rtri_re_3 = unitDelaySig_re[3];

  assign Rtri_re_4 = unitDelaySig_re[4];

  assign Rtri_re_5 = unitDelaySig_re[5];

  assign Rtri_re_6 = unitDelaySig_re[6];

  assign Rtri_re_7 = unitDelaySig_re[7];

  assign Rtri_re_8 = unitDelaySig_re[8];

  assign Rtri_re_9 = unitDelaySig_re[9];

  assign Rtri_im_0 = unitDelaySig_im[0];

  assign Rtri_im_1 = unitDelaySig_im[1];

  assign Rtri_im_2 = unitDelaySig_im[2];

  assign Rtri_im_3 = unitDelaySig_im[3];

  assign Rtri_im_4 = unitDelaySig_im[4];

  assign Rtri_im_5 = unitDelaySig_im[5];

  assign Rtri_im_6 = unitDelaySig_im[6];

  assign Rtri_im_7 = unitDelaySig_im[7];

  assign Rtri_im_8 = unitDelaySig_im[8];

  assign Rtri_im_9 = unitDelaySig_im[9];

  assign valid_1 = 1'b0;

  assign valid_2 = 1'b1;

  assign tmp_29 = (scount_2 == 1'b0 ? valid_1 :
              valid_2);

  assign tmp_30 = (tmp_4 == 1'b0 ? valid_1 :
              tmp_29);

  assign tmp_31 = (samp_valid == 1'b0 ? valid_1 :
              tmp_30);

  always @(posedge clk or posedge reset)
    begin : delayMatch_3_process
      if (reset == 1'b1) begin
        delayMatch_reg_3 <= {2{1'b0}};
      end
      else begin
        if (enb_1_80_0) begin
          delayMatch_reg_3[0] <= tmp_31;
          delayMatch_reg_3[1] <= delayMatch_reg_3[0];
        end
      end
    end

  assign tmp_32 = delayMatch_reg_3[1];

  assign valid = tmp_32;

  assign ce_out = enb_1_80_1;

endmodule  // covariance_core_fixpt

