// -------------------------------------------------------------
// 
// File Name: C:\Users\Shashank Madhusudan\OneDrive\Desktop\Radar-Aided-Beam-Tracking\codegen\covariance_core\hdlsrc\covariance_core_fixptp43.v
// Created: 2026-07-19 11:40:36
// 
// Generated by MATLAB 25.1, MATLAB Coder 25.1 and HDL Coder 25.1
// 
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: covariance_core_fixptp43
// Source Path: 
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module covariance_core_fixptp43
          (clk,
           reset,
           enb_1_5_0,
           j,
           i,
           idx,
           Rtri_re_0,
           Rtri_re_1,
           Rtri_re_2,
           Rtri_re_3,
           Rtri_re_4,
           Rtri_re_5,
           Rtri_re_6,
           Rtri_re_7,
           Rtri_re_8,
           Rtri_re_9,
           Rtri_im_0,
           Rtri_im_1,
           Rtri_im_2,
           Rtri_im_3,
           Rtri_im_4,
           Rtri_im_5,
           Rtri_im_6,
           Rtri_im_7,
           Rtri_im_8,
           Rtri_im_9,
           Rs_re_0,
           Rs_re_1,
           Rs_re_2,
           Rs_re_3,
           Rs_re_4,
           Rs_re_5,
           Rs_re_6,
           Rs_re_7,
           Rs_re_8,
           Rs_re_9,
           Rs_re_10,
           Rs_re_11,
           Rs_re_12,
           Rs_re_13,
           Rs_re_14,
           Rs_re_15,
           Rs_im_0,
           Rs_im_1,
           Rs_im_2,
           Rs_im_3,
           Rs_im_4,
           Rs_im_5,
           Rs_im_6,
           Rs_im_7,
           Rs_im_8,
           Rs_im_9,
           Rs_im_10,
           Rs_im_11,
           Rs_im_12,
           Rs_im_13,
           Rs_im_14,
           Rs_im_15,
           enb,
           Rtri_re_0_1,
           Rtri_re_1_1,
           Rtri_re_2_1,
           Rtri_re_3_1,
           Rtri_re_4_1,
           Rtri_re_5_1,
           Rtri_re_6_1,
           Rtri_re_7_1,
           Rtri_re_8_1,
           Rtri_re_9_1,
           Rtri_im_0_1,
           Rtri_im_1_1,
           Rtri_im_2_1,
           Rtri_im_3_1,
           Rtri_im_4_1,
           Rtri_im_5_1,
           Rtri_im_6_1,
           Rtri_im_7_1,
           Rtri_im_8_1,
           Rtri_im_9_1);


  input   clk;
  input   reset;
  input   enb_1_5_0;
  input   signed [31:0] j;  // int32
  input   signed [31:0] i;  // int32
  input   [3:0] idx;  // ufix4
  input   signed [15:0] Rtri_re_0;  // sfix16_En14
  input   signed [15:0] Rtri_re_1;  // sfix16_En14
  input   signed [15:0] Rtri_re_2;  // sfix16_En14
  input   signed [15:0] Rtri_re_3;  // sfix16_En14
  input   signed [15:0] Rtri_re_4;  // sfix16_En14
  input   signed [15:0] Rtri_re_5;  // sfix16_En14
  input   signed [15:0] Rtri_re_6;  // sfix16_En14
  input   signed [15:0] Rtri_re_7;  // sfix16_En14
  input   signed [15:0] Rtri_re_8;  // sfix16_En14
  input   signed [15:0] Rtri_re_9;  // sfix16_En14
  input   signed [15:0] Rtri_im_0;  // sfix16_En14
  input   signed [15:0] Rtri_im_1;  // sfix16_En14
  input   signed [15:0] Rtri_im_2;  // sfix16_En14
  input   signed [15:0] Rtri_im_3;  // sfix16_En14
  input   signed [15:0] Rtri_im_4;  // sfix16_En14
  input   signed [15:0] Rtri_im_5;  // sfix16_En14
  input   signed [15:0] Rtri_im_6;  // sfix16_En14
  input   signed [15:0] Rtri_im_7;  // sfix16_En14
  input   signed [15:0] Rtri_im_8;  // sfix16_En14
  input   signed [15:0] Rtri_im_9;  // sfix16_En14
  input   signed [15:0] Rs_re_0;  // sfix16_En14
  input   signed [15:0] Rs_re_1;  // sfix16_En14
  input   signed [15:0] Rs_re_2;  // sfix16_En14
  input   signed [15:0] Rs_re_3;  // sfix16_En14
  input   signed [15:0] Rs_re_4;  // sfix16_En14
  input   signed [15:0] Rs_re_5;  // sfix16_En14
  input   signed [15:0] Rs_re_6;  // sfix16_En14
  input   signed [15:0] Rs_re_7;  // sfix16_En14
  input   signed [15:0] Rs_re_8;  // sfix16_En14
  input   signed [15:0] Rs_re_9;  // sfix16_En14
  input   signed [15:0] Rs_re_10;  // sfix16_En14
  input   signed [15:0] Rs_re_11;  // sfix16_En14
  input   signed [15:0] Rs_re_12;  // sfix16_En14
  input   signed [15:0] Rs_re_13;  // sfix16_En14
  input   signed [15:0] Rs_re_14;  // sfix16_En14
  input   signed [15:0] Rs_re_15;  // sfix16_En14
  input   signed [15:0] Rs_im_0;  // sfix16_En14
  input   signed [15:0] Rs_im_1;  // sfix16_En14
  input   signed [15:0] Rs_im_2;  // sfix16_En14
  input   signed [15:0] Rs_im_3;  // sfix16_En14
  input   signed [15:0] Rs_im_4;  // sfix16_En14
  input   signed [15:0] Rs_im_5;  // sfix16_En14
  input   signed [15:0] Rs_im_6;  // sfix16_En14
  input   signed [15:0] Rs_im_7;  // sfix16_En14
  input   signed [15:0] Rs_im_8;  // sfix16_En14
  input   signed [15:0] Rs_im_9;  // sfix16_En14
  input   signed [15:0] Rs_im_10;  // sfix16_En14
  input   signed [15:0] Rs_im_11;  // sfix16_En14
  input   signed [15:0] Rs_im_12;  // sfix16_En14
  input   signed [15:0] Rs_im_13;  // sfix16_En14
  input   signed [15:0] Rs_im_14;  // sfix16_En14
  input   signed [15:0] Rs_im_15;  // sfix16_En14
  input   enb;
  output  signed [15:0] Rtri_re_0_1;  // sfix16_En14
  output  signed [15:0] Rtri_re_1_1;  // sfix16_En14
  output  signed [15:0] Rtri_re_2_1;  // sfix16_En14
  output  signed [15:0] Rtri_re_3_1;  // sfix16_En14
  output  signed [15:0] Rtri_re_4_1;  // sfix16_En14
  output  signed [15:0] Rtri_re_5_1;  // sfix16_En14
  output  signed [15:0] Rtri_re_6_1;  // sfix16_En14
  output  signed [15:0] Rtri_re_7_1;  // sfix16_En14
  output  signed [15:0] Rtri_re_8_1;  // sfix16_En14
  output  signed [15:0] Rtri_re_9_1;  // sfix16_En14
  output  signed [15:0] Rtri_im_0_1;  // sfix16_En14
  output  signed [15:0] Rtri_im_1_1;  // sfix16_En14
  output  signed [15:0] Rtri_im_2_1;  // sfix16_En14
  output  signed [15:0] Rtri_im_3_1;  // sfix16_En14
  output  signed [15:0] Rtri_im_4_1;  // sfix16_En14
  output  signed [15:0] Rtri_im_5_1;  // sfix16_En14
  output  signed [15:0] Rtri_im_6_1;  // sfix16_En14
  output  signed [15:0] Rtri_im_7_1;  // sfix16_En14
  output  signed [15:0] Rtri_im_8_1;  // sfix16_En14
  output  signed [15:0] Rtri_im_9_1;  // sfix16_En14


  wire enb_1_5_0_gated;
  reg [63:0] loopIndex;  // uint64
  wire [3:0] tmp;  // ufix4
  wire loopIndex_first_iter;
  wire signed [15:0] Rtri_re [0:9];  // sfix16_En14 [10]
  wire signed [15:0] Rtri_im [0:9];  // sfix16_En14 [10]
  reg signed [15:0] Rtri_im_10 [0:9];  // sfix16_En14 [10]
  reg signed [15:0] Rtri_re_10 [0:9];  // sfix16_En14 [10]
  wire signed [15:0] Rtri_im_11 [0:9];  // sfix16_En14 [10]
  wire signed [15:0] Rtri_re_11 [0:9];  // sfix16_En14 [10]
  reg signed [15:0] Rtri_reg_reg_re [0:9];  // sfix16_En14 [10]
  reg signed [15:0] Rtri_reg_reg_im [0:9];  // sfix16_En14 [10]
  wire signed [15:0] Rtri_reg_reg_next_re [0:9];  // sfix16_En14 [10]
  wire signed [15:0] Rtri_reg_reg_next_im [0:9];  // sfix16_En14 [10]
  wire signed [15:0] Rtri_re_12 [0:9];  // sfix16_En14 [10]
  wire signed [15:0] Rtri_im_12 [0:9];  // sfix16_En14 [10]
  wire signed [31:0] j_1;  // int32
  reg signed [31:0] j_2;  // int32
  wire signed [31:0] j_3;  // int32
  wire [3:0] tmp_1;  // ufix4
  reg [3:0] idx_1;  // ufix4
  wire [3:0] idx_2;  // ufix4
  wire signed [31:0] i_1;  // int32
  reg signed [31:0] i_2;  // int32
  wire signed [31:0] i_3;  // int32
  wire signed [31:0] s;  // int32
  wire tmp_2;
  wire signed [31:0] s_1;  // int32
  wire signed [31:0] j_4;  // int32
  wire signed [31:0] j_5;  // int32
  wire signed [31:0] s_2;  // int32
  wire tmp_3;
  wire signed [31:0] s_3;  // int32
  wire signed [31:0] i_4;  // int32
  wire signed [31:0] i_5;  // int32
  wire signed [31:0] i_6;  // int32
  wire signed [31:0] s_4;  // int32
  wire signed [31:0] i_7;  // int32
  wire signed [31:0] tmp_4;  // int32
  wire signed [31:0] s_5;  // int32
  wire signed [31:0] tmp_5;  // int32
  wire [7:0] tmp_6;  // uint8
  wire signed [31:0] tmp_7;  // int32
  wire signed [31:0] p35tmp_1;  // int32
  wire tmp_8;
  wire [39:0] tmp_9;  // ufix40_En30
  wire [39:0] s_6;  // ufix40_En30
  wire [40:0] adder_add_cast;  // ufix41_En30
  wire [40:0] adder_add_cast_1;  // ufix41_En30
  wire [40:0] adder_add_temp;  // ufix41_En30
  wire [39:0] tmp_10;  // ufix40_En30
  wire [3:0] tmp_11;  // ufix4
  wire signed [15:0] Rtri_re_13 [0:9];  // sfix16_En14 [10]
  wire signed [15:0] Rtri_im_13 [0:9];  // sfix16_En14 [10]
  wire signed [15:0] Rs_re [0:3] [0:3];  // sfix16_En14 [4x4]
  wire signed [15:0] Rs_im [0:3] [0:3];  // sfix16_En14 [4x4]
  wire signed [15:0] c34_Rs_re [0:15];  // sfix16_En14 [16]
  wire signed [15:0] c34_Rs_im [0:15];  // sfix16_En14 [16]
  wire signed [31:0] tmp_12;  // int32
  wire signed [15:0] Rs_re_16;  // sfix16_En14
  wire signed [15:0] Rs_im_16;  // sfix16_En14
  wire sel;
  wire s_7;
  wire sel_2;
  wire signed [31:0] tmp_13;  // int32
  wire signed [31:0] tmp_14;  // int32
  reg signed [15:0] Rtri_re_14 [0:9];  // sfix16_En14 [10]
  reg signed [15:0] Rtri_im_14 [0:9];  // sfix16_En14 [10]
  reg signed [15:0] Rtri_hold_reg_re [0:9];  // sfix16_En14 [10]
  reg signed [15:0] Rtri_hold_reg_im [0:9];  // sfix16_En14 [10]
  wire signed [15:0] Rtri_hold_reg_next_re [0:9];  // sfix16_En14 [10]
  wire signed [15:0] Rtri_hold_reg_next_im [0:9];  // sfix16_En14 [10]
  wire signed [15:0] Rtri_hold_re [0:9];  // sfix16_En14 [10]
  wire signed [15:0] Rtri_hold_im [0:9];  // sfix16_En14 [10]
  reg signed [31:0] Rtri_reg_t_0_0;  // int32
  reg signed [31:0] Rtri_reg_t_1;  // int32
  reg signed [31:0] p5_t_0_0;  // int32
  reg signed [31:0] p5_t_1;  // int32
  reg signed [31:0] p29Rtri_t_0;  // int32
  reg signed [31:0] Rtri_hold_t_0_0;  // int32
  reg signed [31:0] Rtri_hold_t_1;  // int32


  assign enb_1_5_0_gated = enb && enb_1_5_0;

  // Modulo, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 15
  always @(posedge clk or posedge reset)
    begin : ctr_0_15_process
      if (reset == 1'b1) begin
        loopIndex <= 64'h0000000000000000;
      end
      else begin
        if (enb_1_5_0_gated) begin
          if (loopIndex >= 64'h000000000000000F) begin
            loopIndex <= 64'h0000000000000000;
          end
          else begin
            loopIndex <= loopIndex + 64'h0000000000000001;
          end
        end
      end
    end

  assign tmp = loopIndex[3:0];

  assign loopIndex_first_iter = tmp == 4'b0000;

  assign Rtri_re[0] = Rtri_re_0;
  assign Rtri_re[1] = Rtri_re_1;
  assign Rtri_re[2] = Rtri_re_2;
  assign Rtri_re[3] = Rtri_re_3;
  assign Rtri_re[4] = Rtri_re_4;
  assign Rtri_re[5] = Rtri_re_5;
  assign Rtri_re[6] = Rtri_re_6;
  assign Rtri_re[7] = Rtri_re_7;
  assign Rtri_re[8] = Rtri_re_8;
  assign Rtri_re[9] = Rtri_re_9;

  assign Rtri_im[0] = Rtri_im_0;
  assign Rtri_im[1] = Rtri_im_1;
  assign Rtri_im[2] = Rtri_im_2;
  assign Rtri_im[3] = Rtri_im_3;
  assign Rtri_im[4] = Rtri_im_4;
  assign Rtri_im[5] = Rtri_im_5;
  assign Rtri_im[6] = Rtri_im_6;
  assign Rtri_im[7] = Rtri_im_7;
  assign Rtri_im[8] = Rtri_im_8;
  assign Rtri_im[9] = Rtri_im_9;

  assign Rtri_im_11[0] = Rtri_im_14[0];
  assign Rtri_im_11[1] = Rtri_im_14[1];
  assign Rtri_im_11[2] = Rtri_im_14[2];
  assign Rtri_im_11[3] = Rtri_im_14[3];
  assign Rtri_im_11[4] = Rtri_im_14[4];
  assign Rtri_im_11[5] = Rtri_im_14[5];
  assign Rtri_im_11[6] = Rtri_im_14[6];
  assign Rtri_im_11[7] = Rtri_im_14[7];
  assign Rtri_im_11[8] = Rtri_im_14[8];
  assign Rtri_im_11[9] = Rtri_im_14[9];

  always @(posedge clk or posedge reset)
    begin : Rtri_reg_process
      if (reset == 1'b1) begin
        for(Rtri_reg_t_1 = 32'sd0; Rtri_reg_t_1 <= 32'sd9; Rtri_reg_t_1 = Rtri_reg_t_1 + 32'sd1) begin
          Rtri_reg_reg_re[Rtri_reg_t_1] <= 16'sb0000000000000000;
          Rtri_reg_reg_im[Rtri_reg_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb_1_5_0_gated) begin
          for(Rtri_reg_t_0_0 = 32'sd0; Rtri_reg_t_0_0 <= 32'sd9; Rtri_reg_t_0_0 = Rtri_reg_t_0_0 + 32'sd1) begin
            Rtri_reg_reg_re[Rtri_reg_t_0_0] <= Rtri_reg_reg_next_re[Rtri_reg_t_0_0];
            Rtri_reg_reg_im[Rtri_reg_t_0_0] <= Rtri_reg_reg_next_im[Rtri_reg_t_0_0];
          end
        end
      end
    end
  genvar t_0;
  generate
    for(t_0 = 32'sd0; t_0 <= 32'sd9; t_0 = t_0 + 32'sd1) begin:Rtri_reg_reg_next_im_gen
      assign Rtri_re_12[t_0] = Rtri_reg_reg_re[t_0];
      assign Rtri_im_12[t_0] = Rtri_reg_reg_im[t_0];
      assign Rtri_reg_reg_next_re[t_0] = Rtri_re_11[t_0];
      assign Rtri_reg_reg_next_im[t_0] = Rtri_im_11[t_0];
    end
  endgenerate

  always @* begin
    if (loopIndex_first_iter == 1'b0) begin
      for(p5_t_1 = 32'sd0; p5_t_1 <= 32'sd9; p5_t_1 = p5_t_1 + 32'sd1) begin
        Rtri_re_10[p5_t_1] = Rtri_re_12[p5_t_1];
        Rtri_im_10[p5_t_1] = Rtri_im_12[p5_t_1];
      end
    end
    else begin
      for(p5_t_0_0 = 32'sd0; p5_t_0_0 <= 32'sd9; p5_t_0_0 = p5_t_0_0 + 32'sd1) begin
        Rtri_re_10[p5_t_0_0] = Rtri_re[p5_t_0_0];
        Rtri_im_10[p5_t_0_0] = Rtri_im[p5_t_0_0];
      end
    end
  end

  always @(posedge clk or posedge reset)
    begin : j_reg_process
      if (reset == 1'b1) begin
        j_2 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_5_0_gated) begin
          j_2 <= j_1;
        end
      end
    end

  assign j_3 = (loopIndex_first_iter == 1'b0 ? j_2 :
              j);

  always @(posedge clk or posedge reset)
    begin : idx_reg_process
      if (reset == 1'b1) begin
        idx_1 <= 4'b0000;
      end
      else begin
        if (enb_1_5_0_gated) begin
          idx_1 <= tmp_1;
        end
      end
    end

  assign idx_2 = (loopIndex_first_iter == 1'b0 ? idx_1 :
              idx);

  always @(posedge clk or posedge reset)
    begin : i_reg_process
      if (reset == 1'b1) begin
        i_2 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_5_0_gated) begin
          i_2 <= i_1;
        end
      end
    end

  assign i_3 = (loopIndex_first_iter == 1'b0 ? i_2 :
              i);

  assign s = 32'sd3;

  assign tmp_2 = j_3 == s;

  assign s_1 = 32'sd1;

  assign j_4 = j_3 + s_1;

  assign j_5 = 32'sd0;

  assign j_1 = (tmp_2 == 1'b0 ? j_4 :
              j_5);

  assign s_2 = 32'sd3;

  assign tmp_3 = i_3 == s_2;

  assign s_3 = 32'sd1;

  assign i_4 = i_3 + s_3;

  assign i_5 = 32'sd0;

  assign i_6 = (tmp_3 == 1'b0 ? i_4 :
              i_5);

  assign i_1 = (tmp_2 == 1'b0 ? i_3 :
              i_6);

  assign s_4 = 32'sd1;

  assign i_7 = i_3 + s_4;

  assign tmp_4 = 32'sd1 - i_7;

  assign s_5 = 32'sd4;

  assign tmp_5 = tmp_4 + s_5;

  assign tmp_6 = tmp_5[7:0];

  assign p35tmp_1 = {24'b0, tmp_6};
  assign tmp_7 = p35tmp_1 - 32'sd1;

  assign tmp_8 = j_3 <= tmp_7;

  assign tmp_9 = {6'b0, {idx_2, 30'b000000000000000000000000000000}};

  assign s_6 = 40'h0040000000;

  assign adder_add_cast = {1'b0, tmp_9};
  assign adder_add_cast_1 = {1'b0, s_6};
  assign adder_add_temp = adder_add_cast + adder_add_cast_1;
  assign tmp_10 = (adder_add_temp[40] != 1'b0 ? 40'hFFFFFFFFFF :
              adder_add_temp[39:0]);

  assign tmp_11 = ((tmp_10[39:34] != 6'b000000) || (tmp_10[33:30] == 4'b1111) ? 4'b1111 :
              tmp_10[33:30] + tmp_10[29]);

  assign tmp_1 = (tmp_8 == 1'b0 ? idx_2 :
              tmp_11);

  assign Rtri_re_13[0] = Rtri_re_10[0];
  assign Rtri_re_13[1] = Rtri_re_10[1];
  assign Rtri_re_13[2] = Rtri_re_10[2];
  assign Rtri_re_13[3] = Rtri_re_10[3];
  assign Rtri_re_13[4] = Rtri_re_10[4];
  assign Rtri_re_13[5] = Rtri_re_10[5];
  assign Rtri_re_13[6] = Rtri_re_10[6];
  assign Rtri_re_13[7] = Rtri_re_10[7];
  assign Rtri_re_13[8] = Rtri_re_10[8];
  assign Rtri_re_13[9] = Rtri_re_10[9];

  assign Rtri_im_13[0] = Rtri_im_10[0];
  assign Rtri_im_13[1] = Rtri_im_10[1];
  assign Rtri_im_13[2] = Rtri_im_10[2];
  assign Rtri_im_13[3] = Rtri_im_10[3];
  assign Rtri_im_13[4] = Rtri_im_10[4];
  assign Rtri_im_13[5] = Rtri_im_10[5];
  assign Rtri_im_13[6] = Rtri_im_10[6];
  assign Rtri_im_13[7] = Rtri_im_10[7];
  assign Rtri_im_13[8] = Rtri_im_10[8];
  assign Rtri_im_13[9] = Rtri_im_10[9];

  assign Rs_re[0][0] = Rs_re_0;
  assign Rs_re[1][0] = Rs_re_1;
  assign Rs_re[2][0] = Rs_re_2;
  assign Rs_re[3][0] = Rs_re_3;
  assign Rs_re[0][1] = Rs_re_4;
  assign Rs_re[1][1] = Rs_re_5;
  assign Rs_re[2][1] = Rs_re_6;
  assign Rs_re[3][1] = Rs_re_7;
  assign Rs_re[0][2] = Rs_re_8;
  assign Rs_re[1][2] = Rs_re_9;
  assign Rs_re[2][2] = Rs_re_10;
  assign Rs_re[3][2] = Rs_re_11;
  assign Rs_re[0][3] = Rs_re_12;
  assign Rs_re[1][3] = Rs_re_13;
  assign Rs_re[2][3] = Rs_re_14;
  assign Rs_re[3][3] = Rs_re_15;

  generate
    genvar idx4;
    for(idx4 = 0; idx4 < 4; idx4 = idx4 + 1) begin : c34_Rs_re_gen1
      genvar idx3;
      for(idx3 = 0; idx3 < 4; idx3 = idx3 + 1) begin : c34_Rs_re_gen
        assign c34_Rs_re[idx3 + (idx4 * 4)] = Rs_re[idx3][idx4];
      end
    end
  endgenerate

  assign Rs_im[0][0] = Rs_im_0;
  assign Rs_im[1][0] = Rs_im_1;
  assign Rs_im[2][0] = Rs_im_2;
  assign Rs_im[3][0] = Rs_im_3;
  assign Rs_im[0][1] = Rs_im_4;
  assign Rs_im[1][1] = Rs_im_5;
  assign Rs_im[2][1] = Rs_im_6;
  assign Rs_im[3][1] = Rs_im_7;
  assign Rs_im[0][2] = Rs_im_8;
  assign Rs_im[1][2] = Rs_im_9;
  assign Rs_im[2][2] = Rs_im_10;
  assign Rs_im[3][2] = Rs_im_11;
  assign Rs_im[0][3] = Rs_im_12;
  assign Rs_im[1][3] = Rs_im_13;
  assign Rs_im[2][3] = Rs_im_14;
  assign Rs_im[3][3] = Rs_im_15;

  generate
    genvar idx2;
    for(idx2 = 0; idx2 < 4; idx2 = idx2 + 1) begin : c34_Rs_im_gen1
      genvar idx1;
      for(idx1 = 0; idx1 < 4; idx1 = idx1 + 1) begin : c34_Rs_im_gen
        assign c34_Rs_im[idx1 + (idx2 * 4)] = Rs_im[idx1][idx2];
      end
    end
  endgenerate

  assign tmp_12 = i_7 + j_3;

  assign Rs_re_16 = c34_Rs_re[(i_7 + (32'sd4 * (tmp_12 - 32'sd1))) - 32'sd1];
  assign Rs_im_16 = c34_Rs_im[(i_7 + (32'sd4 * (tmp_12 - 32'sd1))) - 32'sd1];

  assign sel = 1'b0;

  assign s_7 = 1'b1;

  assign sel_2 = (tmp_8 == 1'b0 ? sel :
              s_7);

  assign tmp_13 = {28'b0, idx_2};

  assign tmp_14 = tmp_13 - 32'sd1;

  always @* begin

    for(p29Rtri_t_0 = 32'sd0; p29Rtri_t_0 <= 32'sd9; p29Rtri_t_0 = p29Rtri_t_0 + 32'sd1) begin
      Rtri_re_14[p29Rtri_t_0] = Rtri_re_13[p29Rtri_t_0];
      Rtri_im_14[p29Rtri_t_0] = Rtri_im_13[p29Rtri_t_0];
    end

    if (sel_2) begin
      Rtri_re_14[tmp_14] = Rs_re_16;
      Rtri_im_14[tmp_14] = Rs_im_16;
    end
  end

  assign Rtri_re_11[0] = Rtri_re_14[0];
  assign Rtri_re_11[1] = Rtri_re_14[1];
  assign Rtri_re_11[2] = Rtri_re_14[2];
  assign Rtri_re_11[3] = Rtri_re_14[3];
  assign Rtri_re_11[4] = Rtri_re_14[4];
  assign Rtri_re_11[5] = Rtri_re_14[5];
  assign Rtri_re_11[6] = Rtri_re_14[6];
  assign Rtri_re_11[7] = Rtri_re_14[7];
  assign Rtri_re_11[8] = Rtri_re_14[8];
  assign Rtri_re_11[9] = Rtri_re_14[9];

  always @(posedge clk or posedge reset)
    begin : Rtri_hold_process
      if (reset == 1'b1) begin
        for(Rtri_hold_t_1 = 32'sd0; Rtri_hold_t_1 <= 32'sd9; Rtri_hold_t_1 = Rtri_hold_t_1 + 32'sd1) begin
          Rtri_hold_reg_re[Rtri_hold_t_1] <= 16'sb0000000000000000;
          Rtri_hold_reg_im[Rtri_hold_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb_1_5_0_gated) begin
          for(Rtri_hold_t_0_0 = 32'sd0; Rtri_hold_t_0_0 <= 32'sd9; Rtri_hold_t_0_0 = Rtri_hold_t_0_0 + 32'sd1) begin
            Rtri_hold_reg_re[Rtri_hold_t_0_0] <= Rtri_hold_reg_next_re[Rtri_hold_t_0_0];
            Rtri_hold_reg_im[Rtri_hold_t_0_0] <= Rtri_hold_reg_next_im[Rtri_hold_t_0_0];
          end
        end
      end
    end
  genvar t_01;
  generate
    for(t_01 = 32'sd0; t_01 <= 32'sd9; t_01 = t_01 + 32'sd1) begin:Rtri_hold_reg_next_im_gen
      assign Rtri_hold_re[t_01] = Rtri_hold_reg_re[t_01];
      assign Rtri_hold_im[t_01] = Rtri_hold_reg_im[t_01];
      assign Rtri_hold_reg_next_re[t_01] = Rtri_re_11[t_01];
      assign Rtri_hold_reg_next_im[t_01] = Rtri_im_11[t_01];
    end
  endgenerate

  assign Rtri_re_0_1 = Rtri_hold_re[0];

  assign Rtri_re_1_1 = Rtri_hold_re[1];

  assign Rtri_re_2_1 = Rtri_hold_re[2];

  assign Rtri_re_3_1 = Rtri_hold_re[3];

  assign Rtri_re_4_1 = Rtri_hold_re[4];

  assign Rtri_re_5_1 = Rtri_hold_re[5];

  assign Rtri_re_6_1 = Rtri_hold_re[6];

  assign Rtri_re_7_1 = Rtri_hold_re[7];

  assign Rtri_re_8_1 = Rtri_hold_re[8];

  assign Rtri_re_9_1 = Rtri_hold_re[9];

  assign Rtri_im_0_1 = Rtri_hold_im[0];

  assign Rtri_im_1_1 = Rtri_hold_im[1];

  assign Rtri_im_2_1 = Rtri_hold_im[2];

  assign Rtri_im_3_1 = Rtri_hold_im[3];

  assign Rtri_im_4_1 = Rtri_hold_im[4];

  assign Rtri_im_5_1 = Rtri_hold_im[5];

  assign Rtri_im_6_1 = Rtri_hold_im[6];

  assign Rtri_im_7_1 = Rtri_hold_im[7];

  assign Rtri_im_8_1 = Rtri_hold_im[8];

  assign Rtri_im_9_1 = Rtri_hold_im[9];

endmodule  // covariance_core_fixptp43

