// -------------------------------------------------------------
// 
// File Name: C:\Users\Shashank Madhusudan\OneDrive\Desktop\Radar-Aided-Beam-Tracking\codegen\covariance_core\hdlsrc\covariance_core_fixpt_tc.v
// Created: 2026-07-19 15:08:39
// 
// Generated by MATLAB 25.1, MATLAB Coder 25.1 and HDL Coder 25.1
// 
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: covariance_core_fixpt_tc
// Source Path: covariance_core_fixpt_tc
// Hierarchy Level: 1
// 
// Master clock enable input: clk_enable
// 
// enb_1_5_0   : 5x slower than clk with last phase
// enb_1_8_0   : 8x slower than clk with last phase
// enb_1_80_0  : 80x slower than clk with last phase
// enb_1_80_1  : 80x slower than clk with phase 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module covariance_core_fixpt_tc
          (clk,
           reset,
           clk_enable,
           enb_1_5_0,
           enb_1_8_0,
           enb_1_80_0,
           enb_1_80_1);


  input   clk;
  input   reset;
  input   clk_enable;
  output  enb_1_5_0;
  output  enb_1_8_0;
  output  enb_1_80_0;
  output  enb_1_80_1;


  reg [2:0] count5;  // ufix3
  wire comp_0_tmp;
  wire phase_0_tmp;
  reg  phase_0;
  wire enb_1_5_0_1;
  reg [2:0] count8;  // ufix3
  wire comp_0_tmp_1;
  wire phase_0_tmp_1;
  reg  phase_0_1;
  wire enb_1_8_0_1;
  reg [6:0] count80;  // ufix7
  wire comp_0_tmp_2;
  wire phase_0_tmp_2;
  reg  phase_0_2;
  wire enb_1_80_0_1;
  wire comp_1_tmp;
  wire phase_1_tmp;
  reg  phase_1;
  wire enb_1_80_1_1;


  // Count limited, Unsigned Counter
  //  initial value   = 1
  //  step value      = 1
  //  count to value  = 4
  always @(posedge clk or posedge reset)
    begin : counter_5_process
      if (reset == 1'b1) begin
        count5 <= 3'b001;
      end
      else begin
        if (clk_enable) begin
          if (count5 >= 3'b100) begin
            count5 <= 3'b000;
          end
          else begin
            count5 <= count5 + 3'b001;
          end
        end
      end
    end

  assign comp_0_tmp = count5 == 3'b100;

  assign phase_0_tmp = comp_0_tmp & clk_enable;

  always @(posedge clk or posedge reset)
    begin : phase_delay_process
      if (reset == 1'b1) begin
        phase_0 <= 1'b0;
      end
      else begin
        if (clk_enable) begin
          phase_0 <= phase_0_tmp;
        end
      end
    end

  assign enb_1_5_0_1 = phase_0 & clk_enable;

  assign enb_1_5_0 = enb_1_5_0_1;

  // Count limited, Unsigned Counter
  //  initial value   = 1
  //  step value      = 1
  //  count to value  = 7
  always @(posedge clk or posedge reset)
    begin : counter_8_process
      if (reset == 1'b1) begin
        count8 <= 3'b001;
      end
      else begin
        if (clk_enable) begin
          count8 <= count8 + 3'b001;
        end
      end
    end

  assign comp_0_tmp_1 = count8 == 3'b111;

  assign phase_0_tmp_1 = comp_0_tmp_1 & clk_enable;

  always @(posedge clk or posedge reset)
    begin : phase_delay_1_process
      if (reset == 1'b1) begin
        phase_0_1 <= 1'b0;
      end
      else begin
        if (clk_enable) begin
          phase_0_1 <= phase_0_tmp_1;
        end
      end
    end

  assign enb_1_8_0_1 = phase_0_1 & clk_enable;

  assign enb_1_8_0 = enb_1_8_0_1;

  // Count limited, Unsigned Counter
  //  initial value   = 1
  //  step value      = 1
  //  count to value  = 79
  always @(posedge clk or posedge reset)
    begin : counter_80_process
      if (reset == 1'b1) begin
        count80 <= 7'b0000001;
      end
      else begin
        if (clk_enable) begin
          if (count80 >= 7'b1001111) begin
            count80 <= 7'b0000000;
          end
          else begin
            count80 <= count80 + 7'b0000001;
          end
        end
      end
    end

  assign comp_0_tmp_2 = count80 == 7'b1001111;

  assign phase_0_tmp_2 = comp_0_tmp_2 & clk_enable;

  always @(posedge clk or posedge reset)
    begin : phase_delay_2_process
      if (reset == 1'b1) begin
        phase_0_2 <= 1'b0;
      end
      else begin
        if (clk_enable) begin
          phase_0_2 <= phase_0_tmp_2;
        end
      end
    end

  assign enb_1_80_0_1 = phase_0_2 & clk_enable;

  assign enb_1_80_0 = enb_1_80_0_1;

  assign comp_1_tmp = count80 == 7'b0000000;

  assign phase_1_tmp = comp_1_tmp & clk_enable;

  always @(posedge clk or posedge reset)
    begin : phase_delay_3_process
      if (reset == 1'b1) begin
        phase_1 <= 1'b1;
      end
      else begin
        if (clk_enable) begin
          phase_1 <= phase_1_tmp;
        end
      end
    end

  assign enb_1_80_1_1 = phase_1 & clk_enable;

  assign enb_1_80_1 = enb_1_80_1_1;

endmodule  // covariance_core_fixpt_tc

